### ISSUE TITLE
 invalid choice: 'resnet20-cifar'?

### ISSUE THREAD

**Issue by KangolHsu** [NervanaSystems/distiller#1]
I use “python3 compress_classifier.py -a resnet20-cifar ../../../data.cifar10 --resume ../examples/ssl/checkpoints/checkpoint_trained_dense.pth.tar --quantize --evaluate”

but error occurs:

compress_classifier.py: error: argument --arch/-a: invalid choice: 'resnet20-cifar' (choose from 'alexnet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'inception_v3', 'mobilenet', 'mobilenet_025', 'mobilenet_050', 'mobilenet_075', 'resnet101', 'resnet152', 'resnet18', 'resnet20_cifar', 'resnet32_cifar', 'resnet34', 'resnet44_cifar', 'resnet50', 'resnet56_cifar', 'simplenet_cifar', 'squeezenet1_0', 'squeezenet1_1', 'vgg11', 'vgg11_bn', 'vgg13', 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19', 'vgg19_bn')

**Comment by KangolHsu** [comment]
resnet20-cifar   --->>resnet20_cifar 
>_<

**Comment by guyjacob** [comment]
Fixed the typo in the README (#2), thanks for spotting it

**Comment by KangolHsu** [comment]
By the way ，where did you save the quantized model？

**Comment by guyjacob** [comment]
You're right, saving the model after quantization was missing. Just pushed a commit to that effect (#3). Note that I also updated the [docs](https://nervanasystems.github.io/distiller/algo_quantization/index.html) with a bit more info on the 8-bit quantization method that's currently implemented.
