### ISSUE TITLE
quant_aware_train_linear_quant doesn't work on resnet20_cifar

### ISSUE THREAD

**Issue by ijackyang** [NervanaSystems/distiller#100]
I tried the quant_aware_train_linear_quant.yaml on the resnet20_cifar model, the model seems to be messed up, and cannot get any reasonable prediction and also cannot train. 

Is the quant_aware_train_linear_quant.yaml is only suitable for the resnet18 ?  It seems not, could anyone help ? Thanks very much.

**Comment by guyjacob** [comment]
Indeed I had a bug in there. I just [committed](https://github.com/NervanaSystems/distiller/commit/51880a226236684ed2518c4b24e03ea411d3af35) a fix - please check if that works for you.

**Comment by guyjacob** [comment]
Excellent
