### ISSUE TITLE
About resume quantized model to summary

### ISSUE THREAD

**Issue by ybCliff** [NervanaSystems/distiller#108]
I tried to resume quantized model to get MACs summary like this

>python3 compress_classifier.py --resume=./resnet20_quantized.pth.tar -a=resnet20_cifar ../../../data..cifar10 --summary=compute

But it failed and came with this error 

>RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

Another problem, the first time I ran compress_classifier.py to train simplenet_cifar, msglogger worked well. When I did it again to train resnet20 (or other models), however, the terminal only show these printed message
>Logging to TesnsorBoard - remember to execute the server:
>tensorboard --logdir='./logs'
>Files already downloaded and verified
>Files already downloaded and verified

No more message was printed, and log file which should be saved in './logs/time_stamp/log' was no longer generated either while the training process was still working. How to fix these two problems? Thx a lot

**Comment by levzlotnik** [comment]
Hi,

Closing this due to staleness.
