### ISSUE TITLE
convTranspose2D and LeakyReLU support

### ISSUE THREAD

**Issue by ijackyang** [NervanaSystems/distiller#110]
Hi

Does Distiller Quantization support convTranspose2D and LeakyReLU ?  I tried a model with these two kinds of layers, it seems that distiller just ignore them and didn't do the quantization on them. 
Thanks very much.

Best Regards
HT

**Comment by guyjacob** [comment]
Indeed, quantization is enabled only for an explicitly defined subset of layer types. We only enabled the modules the layers that we've tested so far. 
Just enabling quantization for another module type is not too difficult. I'll detail it below. Please give it a shot and if it's working, you can make a PR.

- Quantizing a layer's activations is done by replacing the module in question with some other module. Sometimes the new module wraps the old module and adds quantization, sometimes it just replaces it completely. That depends on the specific quantization method. In any case, you'll need to add an entry in the `replacement_factory` dict. Each `Quantizer` sub-class handles this in its `__init__` function. For example:
  https://github.com/NervanaSystems/distiller/blob/a89b3ad19da164f517e5b9e9e568c94069cc0c83/distiller/quantization/clipped_linear.py#L126

- When it comes to weights quantization, it depends on how you're applying quantization:
  - Quantization-aware training: In this case weights quantization is handled via the `QuantizationPolicy` and `Quantizer`. See the following line - add the module type you need there: 
 https://github.com/NervanaSystems/distiller/blob/a89b3ad19da164f517e5b9e9e568c94069cc0c83/distiller/quantization/quantizer.py#L153

  - Post-training quantization: In this case, weights quantization is handled in "replacement" layers, similar to how activations are handled. See in `PostTrainLinearQuantizer.__init__()`:
  https://github.com/NervanaSystems/distiller/blob/a89b3ad19da164f517e5b9e9e568c94069cc0c83/distiller/quantization/range_linear.py#L350-L351

**Comment by levzlotnik** [comment]
Hi,

Closing due to staleness.
