### ISSUE TITLE
hard pruning model size

### ISSUE THREAD

**Issue by G-Wang** [NervanaSystems/distiller#120]
Hello, thanks for the awesome repo.

I had a general question regarding model pruning, specifically hard pruning, does distiller create a smaller pruned network or just a network with masks over neurons that're pruned?

**Comment by nzmora** [comment]
Hi Gary,

I'm happy to hear you find this repo useful :-).
Yes, Distiller supports "hard pruning" - we call this "thinning".  I haven't written much about the process, but you can find some info [here](https://nervanasystems.github.io/distiller/tutorial-struct_pruning/index.html) and [here](https://github.com/NervanaSystems/distiller/issues/73#issuecomment-437190079) and [here](https://github.com/NervanaSystems/distiller/pull/6#issue-193843722).

I hope this helps,
Neta

**Comment by G-Wang** [comment]
Hi Neta,

Thanks for the info! I'm not too familiar with network pruning so pardon any questions that perhaps have been answered already.

I just want to confirm after looking through the repo and links:
https://github.com/NervanaSystems/distiller/blob/a0bf2a8f561cb07d76635438c356596bbc669142/distiller/thinning.py#L357

that currently fully connected and conv layers are supported for thinning?

Are `nn.RNN` and `nn.RNNCell` and its variants supported for thinning? I see that there is a tutorial on pruning a RNN language model (https://nervanasystems.github.io/distiller/tutorial-lang_model/index.html#compressing-the-language-model), however I'm not sure if it implements thinning/hard pruning or soft pruning only.

Thanks for the quick response.
Gary

**Comment by nzmora** [comment]
Hi Gary,

Currently thinning ("hard pruning") physically removes filters/channels from a model.  So this applies only for Convolutional layers.  When we remove filters from the weights of a Convolutional layer, the layer that follows has to be adjusted (e.g. its input has less feature-maps). If the layer that follows is a fully-connected layer, then we know how to handle that (i.e. remove columns).

BUT, we currently don't support thinning of rows/cols of a FC layer in other circumstances.  It shouldn't be hard to add, but we don't support that now.  And this applies to RNN/LSTM layer as well.  
For FC/RNN/LSTM we support element-wise pruning in which the weight tensors are sparse, but they remain the same size.

Cheers,
Neta
