### ISSUE TITLE
 no T*T in distillation loss

### ISSUE THREAD

**Issue by kuanzi** [NervanaSystems/distiller#122]
Why  there was no T*T posed on the soft loss in the final distillation loss ? Actually, in [Hinton, 2015], it  is important to utilize T**2 to balance the tradeoff.

[1] Hinton, Geoffrey, Oriol Vinyals, and Jeffrey Dean. "Distilling the knowledge in a neural network." (2015).

**Comment by guyjacob** [comment]
@kuanzi you're correct. Not sure how I neglected it during the implementation. Will fix. Thanks.
