### ISSUE TITLE
What does MACs means on summary output table?

### ISSUE THREAD

**Issue by zheLim** [NervanaSystems/distiller#138]
What does MACs means on summary output table?
Sometimes it means memory access cost(ref: https://arxiv.org/pdf/1807.11164.pdf, section 1).
Sometimes it is MADDs - the number of multiply-accumulates needed to compute an inference on a single image(ref: https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet).
On distiller, what is it?

**Comment by nzmora** [comment]
Hi @zheLim,

In Distiller MACs refers to Multiply-Accumulate operations.
So for example if we have a 1-D tensor with length *K* and we multiply it by a matrix with shape *(K, N), then the output has shape (1, N) and computing it requires K * N MACs.
This is 1-MAC:
```
output[n] += vec[k] * input[k, n]
```
Cheers
Neta

**Comment by zheLim** [comment]
@nzmora 
Thanks a lot!
