### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by Keiku** [NervanaSystems/distiller#140]
I would like Python 3.6 to be supported. When will it be possible? Are there plans?

**Comment by nzmora** [comment]
Hi @Keiku,
I've been using Python 3.6 w/ Distiller for a while w/o any special issues, so I don't think you should have any problem doing the same.
If you do run into issues, please let us know.
Thanks
Neta

**Comment by nzmora** [comment]
I'm keeping this issue open so other can see (and possibly refute) my answer: I use Python 3.6.7, 3.6.6, and 3.5.2 in my systems without any issues or special considerations to the Python version.  

If anyone has problems, please report here.

**Comment by Keiku** [comment]
Sorry for the late reply. It was confirmed that it can be used with Python 3.6. There is no problem even if you close the issue. Thank you very much.
