### ISSUE TITLE
Run distiller on CPU

### ISSUE THREAD

**Issue by marcusvlc** [NervanaSystems/distiller#148]
I'm trying to run the distiller on the CPU, but I'm getting a "keyerror" in the load_state_dict method. After debugging the code, I noticed that the error is in the state parameter of the method, which receives a dictionary with different name keys with each call, and when searching in that dictionary, the error happens. I already tried to execute the commands available in the README with the --cpu argument but did not get any positive results. What are the changes needed to run the master with cpu?

**Comment by nzmora** [comment]
Hi @marcusvlc ,

Please send your exact command-line so we'll be able to recreate.
Thanks

**Comment by marcusvlc** [comment]
The error is:

Log file for this run: /home/vinicius/testes/distiller/examples/classifier_compression/logs/2019.02.07-084425/2019.02.07-084425.log
==> using cifar10 dataset
=> creating resnet20_cifar model for CIFAR10

--------------------------------------------------------
Logging to TensorBoard - remember to execute the server:
> tensorboard --logdir='./logs'

=> loading checkpoint ../ssl/checkpoints/checkpoint_trained_dense.pth.tar
Checkpoint keys:
state_dict
	epoch
	arch
	best_top1
	compression_sched
	optimizer
   best top@1: 92.540

Log file for this run: /home/vinicius/testes/distiller/examples/classifier_compression/logs/2019.02.07-084425/2019.02.07-084425.log
Traceback (most recent call last):
  File "compress_classifier.py", line 723, in <module>
    main()
  File "compress_classifier.py", line 173, in main
    model, compression_scheduler, start_epoch = apputils.load_checkpoint(model, chkpt_file=args.resume)
  File "/home/vinicius/testes/distiller/apputils/checkpoint.py", line 97, in load_checkpoint
    compression_scheduler.load_state_dict(checkpoint['compression_sched'])
  File "/home/vinicius/testes/distiller/distiller/scheduler.py", line 213, in load_state_dict
    masker.mask = loaded_masks[name]
KeyError: 'layer1.0.bn2.bias'

**Comment by nzmora** [comment]
Thanks - I've recreated.  
Sorry if this is delaying you - I'll try fixing in the next couple of days.
Neta

**Comment by nzmora** [comment]
Hi @marcusvlc,

Please try this branch: https://github.com/NervanaSystems/distiller/tree/issue_148

Thanks!
Neta
