### ISSUE TITLE
symlink operation not supported on 'latest_log_dir'

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#157]
python3 distiller/examples/classifier_compression/compress_classifier.py --arch=[...] --workers=[...] --compress=examples/agp-pruning/[...].yaml --batch-size=[...] --epochs=[..] --lr [...] --num-best-scores=[..] imagenet -o=[...]

Log file for this run: [...]/2019.02.17-120315/2019.02.17-120315.log
Traceback (most recent call last):
  File "distiller/examples/classifier_compression/compress_classifier.py", line 748, in <module>
    main()
  File "distiller/examples/classifier_compression/compress_classifier.py", line 97, in main
    msglogger = apputils.config_pylogger(os.path.join(script_dir, 'logging.conf'), args.name, args.output_dir)
  File "distiller/apputils/execution_env.py", line 134, in config_pylogger
    os.symlink(logdir, "latest_log_dir")
OSError: [Errno 95] Operation not supported: '[...]/2019.02.17-120315' -> 'latest_log_dir'

Commenting out that part seems to avoid that issue completely: https://github.com/NervanaSystems/distiller/blame/master/apputils/execution_env.py#L126-L135

**Comment by barrh** [comment]
There's an additional issue (not solved by just commenting out the snippet above):
When specified the experiment name (read, --name=NAME), the result is something like this: NAME___2019.02.17-120734

**Comment by barrh** [comment]
I found the rootcause: symlinks aren't always possible to generate.
I had tried to call compress_classifier.py from a mounted nfs drive, and sent the logs to a local drive.

**Comment by nzmora** [comment]
Re: https://github.com/NervanaSystems/distiller/issues/157#issuecomment-464437700
This has been the intended behavior since the introduction of this feature.

Cheers
Neta
