### ISSUE TITLE
nvidia Turing GPUs support

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#158]
Distiller does not support the latest GPU generation from nvidia, Turing.

Turing GPUs require CUDA 9 or higher, but the Pypi package of torch 0.4.0 is compiled for CUDA 8.
That means, that when Distiller calls 'pip install torch==0.4.0', it installs an older build of torch 0.4.0.
To my knowledge, Pypi hosts a single build for every release. So Pypi's torch 0.4.0 is guaranteed to break on Turing forever.

It doesn't have to be that way. Outside Pypi, other official builds of torch 0.4.0 exist: https://pytorch.org/get-started/previous-versions/
so we could replace the call to pypi server in requirements.txt with: 'pip install ALTERNATIVE_HOST_URL.whl) and it would solve the problem. Alas, these builds tend to be Python minor-version specific (read, Py3.5, Py3.6, Py3.7, etc.), which renders this naive solution impractical.

This issue will only be temporarily solved with the transition to Pytorch 1.0.
Pypi's latest build of Pytorch 1.0.1 is built against CUDA9.X, and though CUDA10-build exist, the Pypi build is linked to CUDA9-build permanently. So this too, will break with future GPUs, sooner or later.

The solution IMO is to have a setup script to query the Python version before installing whatever Torch package from *Pytorch's* package host.

There's also similar issue with Tensorflow builds that is also present in the requirements.txt file, but let's ignore that for now.

**Comment by guyjacob** [comment]
Something like you describe would be nice to have. And we plan to add proper installation with setuptools soon, there will even a script where it could be implemented.
Even so, my opinion is that it isn't something we should be spending time on. I think it'll be difficult to get 100% correct for 100% of cases, which is what you want if you you're going to do something like this, right? For example, if you take a look at the "main" installation [page](https://pytorch.org/get-started/locally/), you'll see there are cases like this:

![image](https://user-images.githubusercontent.com/28220349/52914980-2c0e4180-32d7-11e9-9a71-c716341f4fd9.png)

I don't see how we can support something like "If this doesn't work try that..." automatically. And while it's true we don't specifically aim to support Python 2.7, there's no guarantee we won't see similar things in other cases.

I think the vast majority of users are served fine using the default PyPi version. We can add a comment in the README pointing to the PyTorch installation page, so folks who have specific needs can find the proper version.

**Comment by barrh** [comment]
If you look here: https://pypi.org/project/torch/#files You'll see that it's actually common practice to dedicate a binary per platform, or group of similar platforms. The only parameter torch does not check is your CUDA version. I don't have the slightest idea why not. That also seems to be the case with Tensorflow Pypi.
Anyway, this issue in somewhat redundant now when Distiller requires Pytorch version (1.0.1) that is built for CUDA9 by default. Turing GPUs are now supported in Distiller master.
