### ISSUE TITLE
When does it support hyper-parameter optimizer for better model training?

### ISSUE THREAD

**Issue by ailias** [NervanaSystems/distiller#162]
Thanks for your contributions on this work. And I can use it to pruning my object detector model, the result is great. Moreover I'm interested about hyper-parameter optimizer on the framework which can training a better model without human action. So do you have the plan for doing it?

**Comment by levzlotnik** [comment]
Hi,

Sorry for the late response, which I assume is irrelevant by now.
At this time there are many frameworks (including PyTorch's Ax) which allow hyperparameter optimization.

Closing this issue due to staleness, sorry for the inconvenience.
