### ISSUE TITLE
How to quantize word language model?

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#165]
There are four main SchedulingPolicy types: PruningPolicy, RegularizationPolicy, LRPolicy, and QuantizationPolicy.

Could you provide the example to show how to quantize a RNN model?

**Comment by guyjacob** [comment]
Apologies for the late reply.

Quantization of RNN based models is a bit more complex for Distiller. The reason being that the implementation of RNN/LSTM modules in PyTorch is mostly done at the C level. Only the parameters of the fully connected layers are exposed at the Python level. So, while we could probably do weights quantization, we won't be able to quantize the intermediate activations within the cells.

We're currently working on a Python only implementation of these modules, while will be quintizable.

**Comment by guyjacob** [comment]
@levzlotnik made a very nice tutorial on post-training quantization based on the word language model sample. See here:
https://github.com/NervanaSystems/distiller/blob/master/examples/word_language_model/quantize_lstm.ipynb

**Comment by Vic97192** [comment]
@guyjacob @levzlotnik 
Thank you very much!  It's really helpful.
