### ISSUE TITLE
Can not get the correct tensor input/output shape when use DynamicType

### ISSUE THREAD

**Issue by zeyu-liu** [NervanaSystems/distiller#168]
I used slice / reshape ops in my networks and as it shown in https://github.com/pytorch/pytorch/blob/94a95a0c7f3c38530a9cbc79932ea89ce092d1c2/torch/onnx/symbolic.py#L41 we can not get the actual properties of this tensor. This will be a problem to calculate MACs. As https://github.com/NervanaSystems/distiller/blob/ee1d160f75bd171d8f9b8afd17a65bcb0327a623/apputils/model_summaries.py#L190 treats these tensor as empty tensor (shape is (0, )), it may cause exception when calculating the MACs and may mislead the pruning procedure.

**Comment by zeyu-liu** [comment]
Some Exceptions occurred when applying pruning on this model:
https://github.com/NervanaSystems/distiller/blob/ee1d160f75bd171d8f9b8afd17a65bcb0327a623/apputils/model_summaries.py#L212
and
https://github.com/NervanaSystems/distiller/blob/ee1d160f75bd171d8f9b8afd17a65bcb0327a623/examples/automated_deep_compression/ADC.py#L807

**Comment by nzmora** [comment]
Hi @zeyu-liu,

Can you provide a minimal example of a model which has these slice/reshape operations which cause the problem?  I would like to recreate it and see when the tensor shape == 0.

Thanks
Neta

**Comment by zeyu-liu** [comment]
> Hi @zeyu-liu,
> 
> Can you provide a minimal example of a model which has these slice/reshape operations which cause the problem? I would like to recreate it and see when the tensor shape == 0.
> 
> Thanks
> Neta

I use an implementation of ShuffleNet from [https://github.com/ericsun99/Shufflenet-v2-Pytorch](here).

**Comment by zeyu-liu** [comment]
> Hi @zeyu-liu,
> 
> Can you provide a minimal example of a model which has these slice/reshape operations which cause the problem? I would like to recreate it and see when the tensor shape == 0.
> 
> Thanks
> Neta

Hi @nzmora ,
Any updates?

**Comment by nzmora** [comment]
Hi @zeyu-liu,

Sorry for the delay and thanks for the details - I've recreated the issue.  In Distiller there are two ways to compute the MACs 
of convolutional layers:
1. By traversing an ONNX representation of the model and using the sizes of Convolution operation inputs and outputs, which are extracted from the ONNX IR; 
2. By performing a forward pass on the PyTorch model and extracting the input/output sizes from the forward callback ([code](https://github.com/NervanaSystems/distiller/blob/d556ac51d0c8a349097c5a7ed1f5c5eb32681405/distiller/model_summaries.py#L203-L228)) 

As you pointed out (1) is broken when the model uses certain slice/reshape operations that translate to a tensor with an unknown size.
Therefore, (1) should be removed and (2) should be integrated into [SummaryGraph](https://github.com/NervanaSystems/distiller/blob/d556ac51d0c8a349097c5a7ed1f5c5eb32681405/distiller/summary_graph.py#L52).

I'll add this to the project issues, but I don't know when we will get to fixing this.

Cheers
Neta
