### ISSUE TITLE
A bug in scheduler.add_policy()?

### ISSUE THREAD

**Issue by bezorro** [NervanaSystems/distiller#176]
Hi, I found that maybe there is a bug in [scheduler.add_policy()](https://github.com/NervanaSystems/distiller/blob/725a89f4e400049be4530630d8a94632b9ad66d0/distiller/scheduler.py#L105).
If you call: scheduler.add_policy(policy, [3]). 
The `self.sched_metadata[policy]` would be `{'starting_epoch': 0, 'ending_epoch': 1, 'frequency': 1}`.
But I think it should be `{'starting_epoch': 3, 'ending_epoch': 4, 'frequency': 1}`
Am I misunderstanding something?

**Comment by barrh** [comment]
While still not perfect solution, this is addressed in pull #132

**Comment by nzmora** [comment]
Hi @bezorro,

Good catch! - this is indeed a bug.
Thanks!
Neta

**Comment by dvolgyes** [comment]
Has this been fixed, merged? It seems there is a solution, but not incorporated. Or do i misunderstand it?

**Comment by nzmora** [comment]
Hi @dvolgyes,
This issue should not have any real functional effect on correctness of the sample code, but I fixed it nonetheless.
Cheers,
Neta
