### ISSUE TITLE
How to see PACTQuantizer's 'clip_val'

### ISSUE THREAD

**Issue by aab60526** [NervanaSystems/distiller#177]
As title, if I have train a quantized model and I want to see PACTQuantizer's 'clip_val'
How can I do that?

**Comment by guyjacob** [comment]
The PACTQuantizer replaces instances of ReLU in the model with instances of [LearnedClippedLinearQuantization](https://github.com/NervanaSystems/distiller/blob/61c7e19d0f9e20c50e3d5c56c46f74c088256f38/distiller/quantization/clipped_linear.py#L78), in which `clip_val` is defined as a `torch.nn.Parameter`. Which means that it is automatically part of the model's `state_dict`.

So if you call `.state_dict()` on your model, `clip_val` should be in there. For example, if the specific layer is called `relu2`, then you should have a key in the state_dict named `relu2.clip_val`.

As another example, if you have a saved checkpoint from Distiller, and you want to see all saved `clip_val`, you could do something like:

```python
import torch
import distiller
checkpoint = torch.load(<path_to_checkpoint>)
state_dict = checkpoint['state_dict']
for k, v in state_dict.items():
    if 'clip_val' in k:
        print(k, v)
```
You'll get something like the following:
```
module.layer1.0.relu.clip_val tensor([7.3883], device='cuda:0')
module.layer1.1.pre_relu.clip_val tensor([7.4121], device='cuda:0')
module.layer1.1.relu.clip_val tensor([7.4085], device='cuda:0')
module.layer1.2.pre_relu.clip_val tensor([7.4099], device='cuda:0')
module.layer1.2.relu.clip_val tensor([7.4098], device='cuda:0')
...
```

**Comment by aab60526** [comment]
I got it. Thanks!!
