### ISSUE TITLE
Can't compress ,Total sparsity is 0 use resnet152

### ISSUE THREAD

**Issue by LIMr1209** [NervanaSystems/distiller#181]

**Comment by LIMr1209** [comment]
a compression schedule configuration not use , Can provide a compression schedule configuration for ResNet52

**Comment by nzmora** [comment]
Hi @LIMr1209 ,

We don't have a compression schedule for ResNet152.  We'd love it if you created a schedule and shared it with the community.
Cheers
Neta

**Comment by LIMr1209** [comment]
@nzmora Do I need to make a sensitivity analysis of the model?  Then it's appropriate to set up a  compression schedule for ResNet152. Or use automated deep compression?

**Comment by nzmora** [comment]
Hi @LIMr1209 
Automated Deep Compression does not work well yet.  You can use something like [this](https://github.com/NervanaSystems/distiller/blob/master/examples/agp-pruning/resnet50.schedule_agp.filters_with_FC.yaml). 
ResNet152 is a very large network and I don't recommend trying to compress it, if this is your first compression attempt.  It uses ImageNet and has lots of parameters so it will take a very long time to compress it.

Cheers
Neta

**Comment by LIMr1209** [comment]
@nzmora Thank you
