### ISSUE TITLE
Quantization aware training resume with checkpoint

### ISSUE THREAD

**Issue by aab60526** [NervanaSystems/distiller#185]
Hello, when I training a resuming model with checkpoint,
It raise an error
![image](https://user-images.githubusercontent.com/31931066/54115821-52cc1d80-4428-11e9-824d-0826a3818d90.png)
And this is my command line
![image](https://user-images.githubusercontent.com/31931066/54115930-96268c00-4428-11e9-8111-8b0a612e7460.png)
Where is the error come from?

**Comment by guyjacob** [comment]
It's not 100% clear from the command line, but I assume you're trying to resume **training** from a previous quantization-aware training session. Unfortunately, that's not supported at the moment (see comment [here](https://github.com/NervanaSystems/distiller/issues/21#issuecomment-403293755)).
(In case you want to load a quantization-aware training checkpoint just for **evaluation**, you can use the workaround detailed [here](https://github.com/NervanaSystems/distiller/issues/59#issuecomment-432546165))

We're currently working on fixing some other issues related to loading checkpoints (see #182), once that's finalized I'll try to get quantization-aware training resume soon after.

**Comment by parap1uie-s** [comment]
Maybe, you could try is:

1. Follow the steps [here](https://github.com/NervanaSystems/distiller/issues/59#issuecomment-432546165) to hack the `distiller` framework.

2. Create two model

```
resume_model = create_model(<your params>)
new_model = create_model(<your params same as resume model>)
```

3. Resume quantized weights to `resume model`

```
    if args.resume:
        resume_model, _, _ = apputils.load_checkpoint(resume_model, chkpt_file=args.resume)
        resume_model.to(args.device)
```

4.  Quantize the new model

```
    if args.compress:
        compression_scheduler = distiller.file_config(new_model, optimizer, args.compress, compression_scheduler)

```

Now, you have a `resume model` which contains quantized trained weights, and a `new model` contains random initial quantized weights.

5. Load weights

```
new_model.load_state_dict(copy.deepcopy(resume_model.state_dict()))
del(resume_model)
```

**Comment by thnguyen996** [comment]
Hi, does anyone figure out any quick way to fix this bug? I really need to run evaluation on quantized model
