### ISSUE TITLE
CirCNN

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#192]
CirCNN or block-circulant matrices seems to be getting popular for model compression:
1. arXiv:1708.08917
2. A 65nm 0.39-to-140.3TOPS/W 1-to-12b Unified Neural-Network Processor Using Block-Circulant-Enabled Transpose-Domain Acceleration with 8.1× Higher TOPS/mm2 and 6T HBST-TRAM-Based 2D Data-Reuse Architecture, ISSCC 2019
3. Accelerating Deep Neural Networks by Combining Block-Circulant Matrices and Low-PrecisionWeights, Electronics, https://www.mdpi.com/2079-9292/8/1/78

Does Distiller plan to implement it?

**Comment by nzmora** [comment]
Hi @HKLee2040 ,

We currently don't have plans to implement CirCNN.
Cheers
Neta
