### ISSUE TITLE
Binarization with DoReFa-Net

### ISSUE THREAD

**Issue by tacker-oh** [NervanaSystems/distiller#198]
This issue is about [DorefaParamsBinarizationSTE](https://github.com/NervanaSystems/distiller/blob/master/distiller/quantization/clipped_linear.py#L139).  

[`torch.sign()`](https://pytorch.org/docs/stable/torch.html#torch.sign) returns one of three possible values: {-1, 0, 1} .   I think this isn't binarization.   
https://github.com/NervanaSystems/distiller/blob/b8fc508528bd3f3d73da7bd62bafa4a5afc9001a/distiller/quantization/clipped_linear.py#L145

**Comment by guyjacob** [comment]
You're correct, this is a bug indeed. When the input is 0 the output should be 1.
So, could be something like:
```python
output = torch.where(input == 0, torch.ones_like(input), torch.sign(input)) * E
```
If you'd like to try and test this and submit a quick PR that'll be great. Otherwise I'll try to get to it soon.

**Comment by guyjacob** [comment]
Another option would be:
```python
output = input.sign() * E
output[output == 0] = 1
```
Not sure if there would be a performance difference between the two.

**Comment by tk04m9** [comment]
Thank you for your quick response.  
Could you wait for a couple of days ?
