### ISSUE TITLE
accuracy drop in knowledge distillation

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#199]
I had tested knowledge distillation before (2018/12), the accuracy is very close to the result shown in preact_resnet_cifar_base_fp32.yaml.
e.g. teacher 44, student 20
# | 20    | 44           | 93.09 | 92.64 | 92.795  |

However, I tested this feature recently, the accuracy is dropped:
python compress_classifier.py -a preact_resnet20_cifar --lr 0.1 -p 50 -b 128 ../../../data.cifar10 -j 1 --epochs 200 --compress=../quantization/fp32_baselines/preact_resnet_cifar_base_fp32.yaml --wd=0.0002 --vs=0 --gpus 0 --kd-teacher preact_resnet44_cifar --kd-resume ../cifar10/teacher_resnet/resnet44_best.pth.tar --kd-temp 5.0 --kd-dw 0.7 --kd-sw 0.3

The accuracy is only around 91.9.  It's very hard to reach the worst case shown in preact_resnet_cifar_base_fp32.yaml, i.e., 92.64.

**Comment by guyjacob** [comment]
Thanks for bringing this up. I assume you're testing this now on the latest Distiller code? Or, more specifically - any revision that is after we moved to PyTorch 1.0 (release 0.3)?
Other than Distiller itself, did anything else change in your environment? GPU driver, CUDA version, ... ?

**Comment by HKLee2040** [comment]
Yes, I test it on the latest Distiller.

2019-03-24 12:04:40,510 - Number of CPUs: 8
2019-03-24 12:04:40,531 - Number of GPUs: 1
2019-03-24 12:04:40,532 - CUDA version: 9.0.176
2019-03-24 12:04:40,533 - CUDNN version: 7402
2019-03-24 12:04:40,533 - Kernel: 4.15.0-46-generic
2019-03-24 12:04:40,533 - Python: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
2019-03-24 12:04:40,533 - PyTorch: 1.0.1
2019-03-24 12:04:40,533 - Numpy: 1.16.0
2019-03-24 12:04:40,671 - Git is dirty
2019-03-24 12:04:40,671 - Active Git branch: master
2019-03-24 12:04:40,684 - Git commit: 90226b1cd38d2210e6fb7da988e28ce721b65804

**Comment by qinb** [comment]
> I had tested knowledge distillation before (2018/12), the accuracy is very close to the result shown in preact_resnet_cifar_base_fp32.yaml.
> e.g. teacher 44, student 20
> 
> # | 20 | 44 | 93.09 | 92.64 | 92.795 |
> However, I tested this feature recently, the accuracy is dropped:
> python compress_classifier.py -a preact_resnet20_cifar --lr 0.1 -p 50 -b 128 ../../../data.cifar10 -j 1 --epochs 200 --compress=../quantization/fp32_baselines/preact_resnet_cifar_base_fp32.yaml --wd=0.0002 --vs=0 --gpus 0 --kd-teacher preact_resnet44_cifar --kd-resume ../cifar10/teacher_resnet/resnet44_best.pth.tar --kd-temp 5.0 --kd-dw 0.7 --kd-sw 0.3
> 
> The accuracy is only around 91.9. It's very hard to reach the worst case shown in preact_resnet_cifar_base_fp32.yaml, i.e., 92.64.

Hi,  I only want to learn and run the teacher-student.  could you share your model ../cifar10/teacher_resnet/resnet44_best.pth.tar ?  Thanks

**Comment by levzlotnik** [comment]
Hi,

Closing this due to staleness. Feel free to reopen if needed.
