### ISSUE TITLE
Sluggish ImageNet Data Loading

### ISSUE THREAD

**Issue by dabadee** [NervanaSystems/distiller#202]
I am running the following example:
distiller/examples/agp-pruning/alexnet.schedule_agp.yaml

using the command line
time python3 compress_classifier.py -a=alexnet --lr=0.005 -p=50 ../../../Imagenet -j 22 --epochs 90 --pretrained --compress=../agp-pruning/alexnet.schedule_agp.yaml

but I am getting very slow data loading. The GPU and CPU mostly stay idle. While HDD IO is near 100 percent

For 250 Mini batches of (256 size) it took 11 minutes and 25 seconds

Am I doing something wrong or is it supposed to be this slow ? And any tips for speeding it up, apart from using SSD ?

please help

My PC specs are
2x 1080 Ti
Core i7 8700
64 GB RAM
Seagate HDD ST2000DM001 2TB 64MB Cache

**Comment by nzmora** [comment]
Hi @dabadee 

This is indeed sluggish.  On my machine I processed the first 250 mini-batches in a little over 2 minutes; and the first 850 mini-batches in under 5 minutes; first 2550 mini-batches in 12 mins.  
I've got 22 cores working hard (60-90%) and the SSD I/O is at 100%.
But I'm using Xeon with 88 cores, 256 GB RAM, 4 GPUs and an SSD so it's hard to compare.

Try lowering the number of data-loaders (that's the ```-j``` argument) - maybe you're thrashing the hard-disk with too many concurrent read requests to large files.  Although on my machine when I used ```-j=11``` I saw ~50% latency increase; and with ```-j=33``` about 50% latency decrease (i.e. better than ```-j=22```).
There's some code here that claims to improve the data-loaders performance, but I haven't tried it.
If you manage to improve performance w/o requiring new HW, I'd be interested in hearing about it.

Thanks!
Neta
