### ISSUE TITLE
1d channel-wise regularization

### ISSUE THREAD

**Issue by MrBurnst** [NervanaSystems/distiller#208]
Hi!
From looking through the source, it seems that group-wise regularization is only implemented for 2d inputs? I'd like to use it on multi-channel 1d signals (for feature / channel selection), so ... would that just be a matter of adapting / _3d_channelwise_reg and _channels_l2 in group_regularizer.py to the right dimensions or am I missing something?

thanks!

**Comment by nzmora** [comment]
Hi @MrBurnst,

You can regularize any structure that you choose by providing a function that computes the L2-norm of all the instances of that group/structure.  So you got it right and you are not missing anything ;-)

Cheers,
Neta

**Comment by FelixLorenz** [comment]
@MrBurnst would you mind showing me your adaptions for your needs?

**Comment by levzlotnik** [comment]
Hi,
Closing this due to staleness. Feel free to reopen if you have further questions.
