### ISSUE TITLE
how to quantize new model? 

### ISSUE THREAD

**Issue by Coulson1026** [NervanaSystems/distiller#210]
the new model is  modified by myself, how to quantize it?

**Comment by guyjacob** [comment]
Is this a image classification model or something else?

**Comment by Coulson1026** [comment]
> Is this an image classification model or something else?

Yes，it's a classification model.

**Comment by Coulson1026** [comment]
> Is this an image classification model or something else?

but it does not belong to the model library of distiller, how do i quantize it

**Comment by guyjacob** [comment]
OK, and the dataset is ImageNet or CIFAR-10?

**Comment by Coulson1026** [comment]
> OK, and the dataset is ImageNet or CIFAR-10?

the dataset is collected by myself

**Comment by guyjacob** [comment]
OK. Seeing that it's an image classification model, you can probably get it to work using the existing image classification sample. Using a custom dataset makes it a bit more tricky.
You could modify our models creation code [here](https://github.com/NervanaSystems/distiller/blob/master/distiller/models/__init__.py) and data loading code [here](https://github.com/NervanaSystems/distiller/blob/master/distiller/apputils/data_loaders.py) to make your model and dataset fully integrated with the existing flow.

BUT, I think the quickest way for you to get results will be to just replace thecalls to the code I mentioned above within the image classification sample with code that'll just return your model and your dataset. I'm referring to:
https://github.com/NervanaSystems/distiller/blob/5271625aeccd10cf0cb84965a6acf02cb72e051b/examples/classifier_compression/compress_classifier.py#L148-L150
For creating the model.

And:
https://github.com/NervanaSystems/distiller/blob/5271625aeccd10cf0cb84965a6acf02cb72e051b/examples/classifier_compression/compress_classifier.py#L213-L219
For loading the dataset. You should return three [DataLoaders](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) - train, validation and test. I'm guessing you already have code that does that, if not then [this](https://github.com/utkuozbulak/pytorch-custom-dataset-examples) looks like a good reference.

So - replace the two calls with code that'll create your model and fetch your dataset and you should be good to go. Some functionality such as model summaries will not work out of the box, but to get the model to run and to quantize it it should be OK.

**Comment by Coulson1026** [comment]
Thank you for your help.
