### ISSUE TITLE
How to apply compression and validate, without Training

### ISSUE THREAD

**Issue by dabadee** [NervanaSystems/distiller#211]
I am trying out a sensitivity analysis technique, in which I just want to apply the compression schedule (using one shot pruner L1RankedStructureParameterPruner) on a pretrained network and run the validation. Is there an easy way to do it ?

I commented the train function in compress_classifier.py but then it does not apply the compression schedule as well.

**Comment by dabadee** [comment]
can anyone help me out on this ? Any pointers ?

**Comment by guyjacob** [comment]
Sorry for the delayed response. 
There is no built-in way to do what you want at the moment.
Regarding what you're seeing - The pruning mask is calculated when `on_epoch_begin` is called, but it is applied at `on_minibatch_begin`. The latter is called inside the `train` function, so if you commented that out it makes sense the parameters aren't actually pruned. As a workaround you could call `on_minibatch_begin` yourself, or let it be called from within `train` and just comment out the rest of the function.

**Comment by levzlotnik** [comment]
Hi,

Closing this issue due to staleness. Feel free to reopen if there are further questions.
