### ISSUE TITLE
How do you compare speeds after Distiller？

### ISSUE THREAD

**Issue by wangshuai66666** [NervanaSystems/distiller#218]
I did not see the introduction of raising speed in code,I wanted to know how much faster Distiller had increased his speed.Like on the resnet20,how much faster than before?How to do it?

**Comment by nzmora** [comment]
Hi @wangshuai66666,

Sorry for the late reply - we somehow missed this issue.
Please check our new Wiki [FAQ page](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)) for answers on this topic.

Cheers,
Neta

**Comment by levzlotnik** [comment]
Hi,
Closing this issue as it seems resolved. Feel free to reopen if needed.
