### ISSUE TITLE
Reduce repository size (documentation images inflate the repo size)

### ISSUE THREAD

**Issue by nzmora** [NervanaSystems/distiller#226]
Unfortunately, we maintain 2 copies of documentation images (one
for the documentation source; another for the generated documentation).
We need to solve this as it makes the repository size unproportionally
large.

**Comment by guyjacob** [comment]
Github Pages supports publishing the site from a separate branch called `gh-pages`. See [here](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages).
I think that might be a solution to this problem, in that the html files don't need to be on the master branch that users check out. But I haven't researched enough to understand what it means to make this change.

**Comment by nzmora** [comment]
When users clone the repository, they clone all branches (and unfortunately all of the history diffs), so a different branch doesn't really help with that.  Keeping source and documentation in different branches is counter-intuitive as we want to manage code and docs in unison.

**Comment by guyjacob** [comment]
Hmm, a bit of Git newbie-ism from my side there. Shame on me :)

BTW, I cloned a clean repo now and excluding `.git` the repository is ~51 MB, with the documentation images a little over 5 MB (2.6 MB per copy). So doesn't look like this is the main thing driving up the repo size. There's another set of images used in the README and wiki which is another ~5MB, and there are the SSL checkpoints and wikitext data that are ~13MB each.

**Comment by nzmora** [comment]
OK, cool.  I wince whenever I add images to the documentation.  Now it won't hurt as much.

The checkpoints and wikitext data are something we should be able to separate pretty easily.
