### ISSUE TITLE
When testing the quantized model, whether to use only int8?

### ISSUE THREAD

**Issue by Coulson1026** [NervanaSystems/distiller#229]
when save the quantized model, It contains w_scale，w_zero_point and w_q. in the testing time, the model  only uses the w_q(int8) or need to convert to float32 through w_scale，w_zero_point and w_q？

**Comment by guyjacob** [comment]
Can you please specify which quantizer you're referring to?

**Comment by Coulson1026** [comment]
@guyjacob We are using the RangeLinearQuant method at present.

**Comment by guyjacob** [comment]
Are you referring to the RangeLinearQuant*Wrapper classes (see [here](https://github.com/NervanaSystems/distiller/blob/437e270b3a928ec8803803973889270b7521cfec/distiller/quantization/range_linear.py#L190))?
They are intended for use at test time only anyway (that is, they're designed only for post-training quantization), so I'm not sure I understand what you mean by "in the testing time".
Could you please clarify what you are trying to do?

**Comment by Coulson1026** [comment]
@guyjacob Yes, we use the RangeLinearQuant*Wrapper classes to quantize the trained model. "in the testing time" means that we use the quantized model to test the new data. If I understand correctly, in the  RangeLinearQuant*Wrapper classes, the weight parameter (w,float32) is converted to w_scale，w_zero_point and w_q, then they are saved in the quantized model. So my question is , when we test new data with the quantized model,  the model only use the w_q or use float32 that converted from w_scale，w_zero_point and w_q

**Comment by guyjacob** [comment]
When a `RangeLinearQuantParamLayerWrapper` module is initialized, the float32 weights are replaced with quantized weights (note that the tensors data type is still float32, but the values are limited to 8-bits integers). From that moment on there is no conversion back to float32. When `forward` is called, the quantized weights are used. Does that answer your question?

**Comment by guyjacob** [comment]
Closing for now, if you still have questions feel free to re-open.
