### ISSUE TITLE
can not load ResNet56 finetuned model for cifar10

### ISSUE THREAD

**Issue by charlesmartin14** [NervanaSystems/distiller#230]
I am trying to load the model zoo checkpoint files for the ResNet56 example, as explained in the blog

https://nervanasystems.github.io/distiller/model_zoo.html

I can load the baseline checkpoint file

https://s3-us-west-1.amazonaws.com/nndistiller/pruning_filters_for_efficient_convnets/checkpoint.resnet56_cifar_baseline.pth.tar

 but not the finetuned file

https://s3-us-west-1.amazonaws.com/nndistiller/pruning_filters_for_efficient_convnets/checkpoint_finetuned.pth.tar

```python

from distiller.models import create_model
from distiller.apputils import *
...

cpfiles = {
    'checkpoint.resnet56_cifar_baseline.pth.tar': 92.92,
    'checkpoint_finetuned.pth.tar': 92.96
}

for checkpoint_file, accuracy in cpfiles.items():

    try:
        resnet56_model = create_model(False, 'cifar10', 'resnet56_cifar', parallel=True)
        load_checkpoint(resnet56_model, checkpoint_file);
 
    except Exception as e:
        print("Did you forget to download the checkpoint file?")
        raise e

```

**Comment by guyjacob** [comment]
Indeed when I try to load the fine-tuned model I get size mismatches. Is this what you're getting as well, or another error?

**Comment by guyjacob** [comment]
In any case - the reason for the size mismatches is that the checkpoint on AWS, for some reason, does not contain the thinning recipe which is supposed to be saved when thinning is performed during training. So, the model is not thinned during then load process, which means the parameters remain in their original shape. But, the model parameters stored in the checkpoint are after thinning - and so we have a mismatch between the shapes we're loading and the model we try to load them to.

I re-ran the fine-tuning on the baseline checkpoint, please download the proper checkpoint from here:
[checkpoint_finetuned.pth.tar.gz](https://github.com/NervanaSystems/distiller/files/3093848/checkpoint_finetuned.pth.tar.gz)
Note you'll need to gunzip it before loading with Distiller.

Hopefully this solves the error you were seeing. If not, let us know.

**Comment by charlesmartin14** [comment]
RuntimeError: Error(s) in loading state_dict for ResNetCifar:
	size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.0.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.0.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.0.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.0.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.0.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.1.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.1.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.1.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.1.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.1.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.1.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.2.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.2.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.2.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.2.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.2.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.2.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.3.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.3.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.3.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.3.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.3.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.3.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.4.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.4.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.4.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.4.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.4.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.4.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.5.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.5.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.5.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.5.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.5.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.5.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.6.conv1.weight: copying a param with shape torch.Size([7, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer1.6.bn1.weight: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.6.bn1.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.6.bn1.running_mean: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.6.bn1.running_var: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for layer1.6.conv2.weight: copying a param with shape torch.Size([16, 7, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3]).
	size mismatch for layer2.0.conv1.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 16, 3, 3]).
	size mismatch for layer2.0.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.0.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.0.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.0.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.0.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.1.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.1.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.1.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.1.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.1.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.1.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.2.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.2.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.2.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.2.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.2.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.2.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.3.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.3.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.3.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.3.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.3.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.3.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.5.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.5.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.5.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.5.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.5.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.5.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.6.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.6.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.6.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.6.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.6.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.6.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.7.conv1.weight: copying a param with shape torch.Size([16, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer2.7.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.7.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.7.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.7.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for layer2.7.conv2.weight: copying a param with shape torch.Size([32, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for layer3.2.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.2.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.2.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.2.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.2.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.2.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.3.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.3.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.3.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.3.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.3.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.3.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.5.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.5.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.5.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.5.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.5.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.5.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.6.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.6.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.6.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.6.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.6.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.6.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.7.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.7.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.7.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.7.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.7.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.7.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.8.conv1.weight: copying a param with shape torch.Size([45, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layer3.8.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.8.bn1.bias: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.8.bn1.running_mean: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.8.bn1.running_var: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for layer3.8.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).

**Comment by charlesmartin14** [comment]
Thanks Ill check it out.

**Comment by nzmora** [comment]
We need to update the file on AWS.  I'm filing this as a bug.

**Comment by BaraaSaeed** [comment]
I can't load those files! neither the baseline checkpoint file nor the fine-tuned one.
Could you please update the Amazonas files?
