### ISSUE TITLE
some problems with quantization

### ISSUE THREAD

**Issue by jizhishou** [NervanaSystems/distiller#231]
Hi,
I'm learning to use the distiller. When I learn to use the quantization, it has the problem. 
In examples/classifier_compression/compress_classifier.py, 
I  change the model to my small net and use the cifar dataset. my small net defined as below:

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

and change the yaml file as below:
version: 1

quantizers:
  dorefa_quantizer:
    class: DorefaQuantizer
    bits_activations: 4
    bits_weights: 4
    bits_bias: 4
    overrides:
      conv1:
        bits_weights: null
        bits_activations: null
      fc3:
        bits_weights: null
        bits_activations: null

lr_schedulers:
   pruning_lr:
     class: ExponentialLR
     gamma: 0.9

policies:
  - quantizer:
      instance_name: 'dorefa_quantizer'
    starting_epoch: 1
    ending_epoch: 30
    frequency: 1

  - lr_scheduler:
      instance_name: pruning_lr
    starting_epoch: 24
    ending_epoch: 30
    frequency: 1

other args is use the default or None.
When I run the compress_classifier.py I get the error:

File "compress_classifier.py", line 786, in <module>
    main()
  File "compress_classifier.py", line 292, in main
    msglogger.info(distiller.masks_sparsity_tbl_summary(model, compression_scheduler))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zhang/distiller/distiller/data_loggers/collector.py", line 469, in collectors_context
    yield collectors_dict
  File "compress_classifier.py", line 287, in main
    loggers=[tflogger, pylogger], args=args)
  File "compress_classifier.py", line 399, in train
    optimizer.step()
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/sgd.py", line 93, in step
    d_p.add_(weight_decay, p.data)
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor

And I also check all the tensor in model. It's the torch.cuda.FloatTenor. How can I fix it?

**Comment by nzmora** [comment]
Hi @jizhishou,

The weight tensors and the optimizer's ```weight_decay``` seem to have different types (both are floats, but one is placed in GPU memory, and the other is in CPU memory).  
Make sure that the model and the model parameters use the same device (CPU or GPU).
Cheers,
Neta

**Comment by jizhishou** [comment]
> Hi @jizhishou,
> 
> The weight tensors and the optimizer's `weight_decay` seem to have different types (both are floats, but one is placed in GPU memory, and the other is in CPU memory).
> Make sure that the model and the model parameters use the same device (CPU or GPU).
> Cheers,
> Neta

Hi nzmora,
I check the model tensors is in GPU memory, So I think the the problem is weight_decay, how can I check it? or how can I solve it?

Regards,
jizhishou

**Comment by guyjacob** [comment]
In general you need to make sure that you construct the optimizer after the model has been moved to the GPU. I see you are running the image classification sample, so that should be taken care of. Have you made any other changes to the script besides supplying your own small model, and the YAML you specified?

**Comment by guyjacob** [comment]
Can you also share the command line you used to run it?

**Comment by jizhishou** [comment]
> Can you also share the command line you used to run it?

Hi guyjacob，

I have not made any other changes. My command line is just `python compress_classifier.py data --compress=test.yaml` 

I also check the `weight_decay` use the code `print(type(optimizer.param_groups[0]['weight_decay'])` before the line `optimizer.step()` It return float .  and the `optimizer.param_groups[0]['params'] ` is live in GPU memory. Is it correct?

Regards,
jishishou

**Comment by nzmora** [comment]
Hi @jizhishou,

After creating the model, try moving it to the gpu.
E.g. something like:
```
model = Net()
model = model.to('cuda')
```
Cheers
Neta

**Comment by jizhishou** [comment]
> Hi @jizhishou,
> 
> After creating the model, try moving it to the gpu.
> E.g. something like:
> 
> ```
> model = Net()
> model = model.to('cuda')
> ```
> 
> Cheers
> Neta

Hi Neta, 
Thank you for reply. I do that, and I check the parameters are in GPU. 

Regards,
jizhishou

**Comment by jizhishou** [comment]
I have solved the problem.

**Comment by tzc1994** [comment]
HI, How should I use the Quantization-Aware Training such as DoReFa?
The terminal command is right?
 python3 compress_classifier.py -a alexnet /ImageNet_Share/ --compress=/home/tzc/distiller/examples/quantization/quant_aware_train/alexnet_bn_dorefa.yaml
But I meet this error：
FATAL Parsing error!
{
 "quantizer": {
  "instance_name": "dorefa_quantizer"
 },
 "starting_epoch": 0,
 "ending_epoch": 200,
 "frequency": 1
}
Exception: <class 'TypeError'> unsupported operand type(s) for ** or pow(): 'int' and 'NoneType'

Log file for this run: /home/tzc/distiller/examples/classifier_compression/logs/2019.05.09-115537/2019.05.09-115537.log
Traceback (most recent call last):
  File "compress_classifier.py", line 776, in <module>
    main()
  File "compress_classifier.py", line 235, in main
    (start_epoch-1) if args.resumed_checkpoint_path else None)
  File "/home/tzc/distiller/distiller/config.py", line 148, in file_config
    return dict_config(model, optimizer, sched_dict, scheduler, resumed_epoch)
  File "/home/tzc/distiller/distiller/config.py", line 93, in dict_config
    policy = distiller.QuantizationPolicy(quantizer)
  File "/home/tzc/distiller/distiller/policy.py", line 226, in __init__
    self.quantizer.quantize_params()
  File "/home/tzc/distiller/distiller/quantization/quantizer.py", line 277, in quantize_params
    q_param = self.param_quantization_fn(getattr(ptq.module, ptq.fp_attr_name), ptq)
  File "/home/tzc/distiller/distiller/quantization/clipped_linear.py", line 133, in dorefa_quantize_param
    scale, zero_point = asymmetric_linear_quantization_params(param_meta.num_bits, 0, 1, signed=False)
  File "/home/tzc/distiller/distiller/quantization/q_utils.py", line 65, in asymmetric_linear_quantization_params
    n = 2 ** num_bits - 1
TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'NoneType'
@jizhishou

**Comment by zhouchch3** [comment]
> I have solved the problem.

Could you tell me how you solved this problem? Thank you very much!
