### ISSUE TITLE
Why quantization made the mode slower?

### ISSUE THREAD

**Issue by YaminSAIC** [NervanaSystems/distiller#238]
Hi, I am new to this package and now trying to use quantization to speed up my network.
I followed the tutorial of post train quantization and printed out the running time for model before and after quantization for the test set:
before quantization: 0.6944317817687988 seconds
after quantization: 1.938002586364746 seconds
I thought quantization will make the network faster. I am running on Ubantu 16.04, TitanXp.

**Comment by guyjacob** [comment]
Hi @YaminSAIC. As it is, Distiller only simulates quantization, with the purpose of exploring the effects of quantization on model accuracy.
Please see #159 and also #22.

**Comment by YaminSAIC** [comment]
HI, @guyjacob . Thanks for the hints. So what about pruning, will this be a simulation too or it can really accelerate the speed?

**Comment by nzmora** [comment]
Hi @YaminSAIC,

For the answerto your question regarding pruning, please see our new [Frequently Asked Questions (FAQ)](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)) page.

Cheers,
Neta

**Comment by YaminSAIC** [comment]
@guyjacob thanks so much, I will close this.
