### ISSUE TITLE
Minor Clean Up of Quantizer.py

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#24]
`Warnings / Weak Warnings`

- In this line : https://github.com/NervanaSystems/distiller/blob/2bb9689fe58d196ccbccd3f2f44ac27192eb64e1/distiller/quantization/quantizer.py#L114 , Local variable `keys_list` might be referenced before assignment, due to the fact that `keys_list` is declared only when we request for `bits_overrides`.

- In this line : https://github.com/NervanaSystems/distiller/blob/2bb9689fe58d196ccbccd3f2f44ac27192eb64e1/distiller/quantization/quantizer.py#L175 Variable `module` is used,  but this Variable `module`  is already declared in `for` loop above .

**Comment by guyjacob** [comment]
Thanks. The second one is definitely a bug, but since we don't reference the `module` declared at the upper-level from that point forward it's not actually causing any issues.
Feel free to make a PR, otherwise we'll fix it in an upcoming commit.
