### ISSUE TITLE
Thinning op fails with Pytorch v1.1

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#243]
Calling `pytest`, with torch v1.1.0 (CUDA 10), fails the pruning tests during executing thinning recipes:

RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()
../distiller/thinning.py:501: RuntimeError

Related torch proposal: https://github.com/pytorch/pytorch/issues/13638

Simply ignoring the runtime-error didn't resolve the issue.

**Comment by nzmora** [comment]
Thanks @barrh ,

What happens when you ignore the runtime-error?
Which part of the link you sent should I look at?  Some of the discussion is from the end of 2018, and some more recent.

Cheers,
Neta

**Comment by barrh** [comment]
hey @nzmora ,

The relevant documentation of the change in the link, starts in the breaking changes, specifically, the allow_tensor_metadata_change_ flag, until the end of the first PR under Upcoming PRs.

When I ignore the runtimeerror, it complains on size mismatch on a subsequent assignment in backward() call.

**Comment by trougnouf** [comment]
I've got a similar error; RuntimeError: Function CudnnConvolutionBackward returned an invalid gradient at index 1 - got [3, 29, 3, 3] but expected shape compatible with [3, 32, 3, 3]

I've attached the log
[bugreport_thinning-2.txt](https://github.com/NervanaSystems/distiller/files/3482500/bugreport_thinning-2.txt)



My code looks like the following:
```
compression_scheduler = distiller.config.file_config(model, optimizer, args.compression_schedule)
for each epoch:
    for each batch:
        compression_scheduler.on_minibatch_begin(epoch, batch_i, batches_per_epoch, optimizer=optimizer)
        train()
        compression_scheduler.before_backward_pass(epoch, batch_i, batches_per_epoch, loss)
        loss.backward()
        compression_scheduler.before_parameter_optimization(epoch, batch_i, batches_per_epoch, optimizer)
        optimizer.step()
        compression_scheduler.on_minibatch_end(epoch, batch_i, batches_per_epoch, optimizer=optimizer)
    compression_scheduler.on_epoch_end(epoch)
```

(I give the input_shape as a parameter instead of the dataset and arch since it's not a classifier, I will make a PR on that once I can test.)

**Comment by trougnouf** [comment]
I have it working when I set
```
                prediction = None
                loss = None   
```     
before `prediction = model(batch_y)` and `loss = criterion(prediction, batch_x)`

I then get a lot of warnings such as 
![Screenshot from 2019-08-09 11-43-42](https://user-images.githubusercontent.com/6899116/62770281-01898e00-ba9b-11e9-800f-39760961dff4.png)

**Comment by nzmora** [comment]
Hi @barrh
I'm closing as integration with pytorch 1.1 has been implemented a while ago (thanks for your help!).

Hi @trougnouf,
I only saw your messages now.  I think your report is unrelated to @barrh's, so if this is still a problem, please open a new issue.

Thanks
Neta

**Comment by wozqhl** [comment]
> I have it working when I set
> 
> ```
>                 prediction = None
>                 loss = None   
> ```
> 
> before `prediction = model(batch_y)` and `loss = criterion(prediction, batch_x)`
> 
> I then get a lot of warnings such as
> ![Screenshot from 2019-08-09 11-43-42](https://user-images.githubusercontent.com/6899116/62770281-01898e00-ba9b-11e9-800f-39760961dff4.png)

Have you solved the question, I met the same errors

**Comment by zeyu-hello** [comment]
> I've got a similar error; `RuntimeError: Function CudnnConvolutionBackward returned an invalid gradient at index 1 - got [3, 29, 3, 3] but expected shape compatible with [3, 32, 3, 3]`
> 
> I've attached the log
> [bugreport_thinning-2.txt](https://github.com/NervanaSystems/distiller/files/3482500/bugreport_thinning-2.txt)
> 
> My code looks like the following:
> 
> ```
> compression_scheduler = distiller.config.file_config(model, optimizer, args.compression_schedule)
> for each epoch:
>     for each batch:
>         compression_scheduler.on_minibatch_begin(epoch, batch_i, batches_per_epoch, optimizer=optimizer)
>         train()
>         compression_scheduler.before_backward_pass(epoch, batch_i, batches_per_epoch, loss)
>         loss.backward()
>         compression_scheduler.before_parameter_optimization(epoch, batch_i, batches_per_epoch, optimizer)
>         optimizer.step()
>         compression_scheduler.on_minibatch_end(epoch, batch_i, batches_per_epoch, optimizer=optimizer)
>     compression_scheduler.on_epoch_end(epoch)
> ```
> 
> (I give the input_shape as a parameter instead of the dataset and arch since it's not a classifier, I will make a PR on that once I can test.)
> 
> edit: The model seems to have the right shape after `compression_scheduler.on_minibatch_begin(epoch, batch_i, batches_per_epoch, optimizer=optimizer)`, and it fails on cpu as well (`RuntimeError: Function MkldnnConvolutionBackward returned an invalid gradient at index 1 - got [3, 29, 3, 3] but expected shape compatible with [3, 32, 3, 3]`)

Hello, I encountered same error. 
I pruned some filters, while the `forward` function works well and `loss.backward()` does not. 
Have you solved it?

**Comment by bwtseng** [comment]
@zeyu-hello, Hi, I have the same issue, did you use custom loss during your pruning stage?

**Comment by simranjit2112** [comment]
Hi @nzmora I am getting same error as above:
`RuntimeError: Function CudnnConvolutionBackward returned an invalid gradient at index 1 - got [64, 32, 3, 3] but expected shape compatible with [64, 64, 3, 3]`

Do you have any idea on how to go about it? I am trying out filter pruning and thinning on a single conv module (64 filters reduced to 32).

@trougnouf can you elaborate on how you resolved the issue?
