### ISSUE TITLE
AMC-pretrained model mismathch？

### ISSUE THREAD

**Issue by itracy19** [NervanaSystems/distiller#244]
Dear everyone,

I am interested in Distiller with the AMC compress method，so i tried to use a pretrained model such as vgg16, but i encountered many problem，so i wonder it the pre-trained model should be saved with constrained format？

Thanks

**Comment by nzmora** [comment]
Hi @itracy19,

The AMC implementation is currently experimental and somewhat hard-coded for specific models.  If you have something specific in mind, maybe I can help.

Cheers
Neta

**Comment by itracy19** [comment]
Hi，Neta，

Thank you for your response.
Right now,i just want to compress models trained by myself, so i think a specific format for models can be loaded correctly may be necessary,is there some information?

Thanks

**Comment by nzmora** [comment]
Hi @itracy19 ,

You can now try our auto-compression [code](https://github.com/NervanaSystems/distiller/tree/master/examples/auto_compression).  It's currently limited and doesn't support VGG, although that can be added rather simply.
I'll add more information on the setup soon.
Cheers
Neta
