### ISSUE TITLE
Setting clip value in `PostTrainLinearQuantizer` raises TypeError

### ISSUE THREAD

**Issue by bdhammel** [NervanaSystems/distiller#249]
I'm trying to clip by specifying the number to standard deviations in `PostTrainLinearQuantizer`

```
    quantizer = quantization.PostTrainLinearQuantizer(
        model,
        bits_activations=8, bits_parameters=8, bits_accum=32,
        mode=quantization.LinearQuantMode.SYMMETRIC,
        clip_acts=quantization.ClipMode.N_STD,
        no_clip_layers=None, clip_n_stds=3
    )
    quantizer.prepare_model()
```

However, this throws the error:

```
TypeError: get_tensor_mean_n_stds_max_abs() got multiple values for argument 'n_stds'
```

It looks like the `sat_fn` is taking two values:
https://github.com/NervanaSystems/distiller/blob/master/distiller/quantization/range_linear.py#L97 
One is the tensor and one is the dimension to be used with `ClipMode.AVG`; the standard deviation is attached as a partial: https://github.com/NervanaSystems/distiller/blob/master/distiller/quantization/range_linear.py#L76 

However, `get_tensor_mean_n_stds_max_abs` only accepts the tensor and the std. https://github.com/NervanaSystems/distiller/blob/master/distiller/quantization/q_utils.py#L149

modifying the source fixed this:

```
def get_tensor_mean_n_stds_min_max(t, _, n_stds=1):
    if n_stds <= 0:
        raise ValueError('n_stds must be > 0, got {}'.format(n_stds))
    mean = t.mean()
    std = t.std()
    min_val, max_val = get_tensor_min_max(t)
    min_val = torch.max(min_val, mean - n_stds * std)
    max_val = torch.min(max_val, mean + n_stds * std)
    return min_val, max_val


def get_tensor_mean_n_stds_max_abs(t, _, n_stds=1):
    min_val, max_val = get_tensor_mean_n_stds_min_max(t, _, n_stds)
    return torch.max(min_val.abs_(), max_val.abs_())
```

Distiller version: 0.4.0-pre
Pytorch version: 1.0.1
Python version: 3.6.8

**Comment by guyjacob** [comment]
@bdhammel Sorry for the late response, and thanks for catching this! Fixed in https://github.com/NervanaSystems/distiller/commit/9af786b6599fe41fc95593e77d4631f0150b24d1.
