### ISSUE TITLE
has Input quantized in Quantization-Aware Training?

### ISSUE THREAD

**Issue by XiaotianM** [NervanaSystems/distiller#253]
https://github.com/NervanaSystems/distiller/blob/1f48fa64131596b181ebd26a59d2679f7f877dee/distiller/quantization/range_linear.py#L989

```
def inputs_quantize_wrapped_forward(self, input):
    input = self.inputs_quant(input)
    return self.original_forward(input)
```

This function seems not work. 
Besides, when I have two input, how to quantize them?

**Comment by guyjacob** [comment]
Hi @XiaotianM. Sorry for the late reply.

**The function is not working:**
Can you provide more details - what makes you think it's not working? Is it not doing what you expect it to do? Is it not being called at all?
This functionality to quantize the inputs is specific to `QuantAwareTrainRangeLinearQuantizer`. Are you sure you're running with this quantizer?

I'm checking it with the following command line:

`python compress_classifier.py -a resnet18 ~/datasets/imagenet --compress=../quantization/quant_aware_train/quant_aware_train_linear_quant.yaml --gpus 0`

(the paths are assuming you're running it from `<distiller_repo_root>/examples/classifier_compression`)

And it seems to be working for me.

**Regarding multiple inputs:**
Indeed the way it's implemented now is hard-coded to a single input. In fact, the `FakeLinearQuantization` module itself assumes a single input, so this would be an issue not only with input of first layer (which is what the code you refer to handles). Any layer we wish to fake-quantize that produces multiple outputs will fail. A proper solution for this would require knowing, at the time of the Quantizer's initialization, the number of inputs/outputs for each layer. In the general case, we don't have this info until the model is actually executed. So fixing this requires some thinking.
What's your specific use case? I'm guessing we could come up with some workaround that will allow you to continue to work.

**Comment by guyjacob** [comment]
It's been a while, so closing this. @XiaotianM please re-open if needed.

**Comment by tom2002965** [comment]
Hello @guyjacob ,

I encounter the same problem.

I want to use quantization-aware training to quantize yolov3(Object detection).
And my model's forward have two argument
`def forward(self, x, targets=None):`
So I got this error issue

```
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    loss, outputs = model(imgs, targets)
  File "/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    
result = self.forward(*input, **kwargs)
TypeError: inputs_quantize_wrapped_forward() takes 2 positional arguments but 3 were given
```
I think it occurred when I pass two arguments.

I have tried to modify range_linear.py , but it closely related other code.
Thus I wanna find other solutions.
Thanks
