### ISSUE TITLE
Meet dimensions mismatch when running example "Getting parameter statistics of a sparsified model"

### ISSUE THREAD

**Issue by ChongyuIntel** [NervanaSystems/distiller#26]
When running the example "Getting parameter statistics of a sparsified model" in the Readme, I meet the following problem. Can you help take a look at it?

Command: $ python3 compress_classifier.py --resume=../ssl/checkpoints/checkpoint_trained_channel_regularized_resnet20_finetuned.pth.tar -a=resnet20_cifar ../../../data.cifar10 --summary=compute

Error:
RuntimeError: Error(s) in loading state_dict for ResNetCifar:
	While copying the parameter named "layer1.0.conv1.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([11, 16, 3, 3]).
	While copying the parameter named "layer1.0.bn1.running_mean", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([11]).
	While copying the parameter named "layer1.0.bn1.running_var", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([11]).
	While copying the parameter named "layer1.0.bn1.weight", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([11]).
	While copying the parameter named "layer1.0.bn1.bias", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([11]).
	While copying the parameter named "layer1.0.conv2.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([16, 11, 3, 3]).
	While copying the parameter named "layer1.1.conv1.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([8, 16, 3, 3]).
	While copying the parameter named "layer1.1.bn1.running_mean", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([8]).
	While copying the parameter named "layer1.1.bn1.running_var", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([8]).
	While copying the parameter named "layer1.1.bn1.weight", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([8]).
	While copying the parameter named "layer1.1.bn1.bias", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([8]).
	While copying the parameter named "layer1.1.conv2.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([16, 8, 3, 3]).
	While copying the parameter named "layer1.2.conv1.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([9, 16, 3, 3]).
	While copying the parameter named "layer1.2.bn1.running_mean", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([9]).
	While copying the parameter named "layer1.2.bn1.running_var", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([9]).
	While copying the parameter named "layer1.2.bn1.weight", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([9]).
	While copying the parameter named "layer1.2.bn1.bias", whose dimensions in the model are torch.Size([16]) and whose dimensions in the checkpoint are torch.Size([9]).
	While copying the parameter named "layer1.2.conv2.weight", whose dimensions in the model are torch.Size([16, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([16, 9, 3, 3]).
	While copying the parameter named "layer2.0.conv1.weight", whose dimensions in the model are torch.Size([32, 16, 3, 3]) and whose dimensions in the checkpoint are torch.Size([22, 16, 3, 3]).
	While copying the parameter named "layer2.0.bn1.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([22]).
	While copying the parameter named "layer2.0.bn1.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([22]).
	While copying the parameter named "layer2.0.bn1.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([22]).
	While copying the parameter named "layer2.0.bn1.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([22]).
	While copying the parameter named "layer2.0.conv2.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 22, 3, 3]).
	While copying the parameter named "layer2.1.conv1.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([20, 32, 3, 3]).
	While copying the parameter named "layer2.1.bn1.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([20]).
	While copying the parameter named "layer2.1.bn1.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([20]).
	While copying the parameter named "layer2.1.bn1.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([20]).
	While copying the parameter named "layer2.1.bn1.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([20]).
	While copying the parameter named "layer2.1.conv2.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 20, 3, 3]).
	While copying the parameter named "layer3.0.conv1.weight", whose dimensions in the model are torch.Size([64, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([52, 32, 3, 3]).
	While copying the parameter named "layer3.0.bn1.running_mean", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([52]).
	While copying the parameter named "layer3.0.bn1.running_var", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([52]).
	While copying the parameter named "layer3.0.bn1.weight", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([52]).
	While copying the parameter named "layer3.0.bn1.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([52]).
	While copying the parameter named "layer3.0.conv2.weight", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 52, 3, 3]).
	While copying the parameter named "layer3.1.conv1.weight", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([56, 64, 3, 3]).
	While copying the parameter named "layer3.1.bn1.running_mean", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([56]).
	While copying the parameter named "layer3.1.bn1.running_var", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([56]).
	While copying the parameter named "layer3.1.bn1.weight", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([56]).
	While copying the parameter named "layer3.1.bn1.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([56]).
	While copying the parameter named "layer3.1.conv2.weight", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 56, 3, 3]).

**Comment by nzmora** [comment]
Thanks @ChongyuIntel!  I must have accidentally committed in the past a checkpoint file without the "thinning recipe" (see commit message).

**Comment by ChongyuIntel** [comment]
Thanks for quick fix. Verified on my side, it works with the problem:

Traceback (most recent call last):
  File "compress_classifier.py", line 503, in <module>
    main()
  File "compress_classifier.py", line 229, in main
    model, chkpt_file=args.resume)
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/apputils/checkpoint.py", line 110, in load_checkpoint
    model.thinning_recipes)
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/distiller/thinning.py", line 419, in execute_thinning_recipes_list
    execute_thinning_recipe(model, zeros_mask_dict, recipe, optimizer=None, loaded_from_file=True)
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/distiller/thinning.py", line 476, in execute_thinning_recipe
    setattr(layers[layer_name], attr, val)
KeyError: 'module.layer3.0.conv2'

I think the root cause of this problem is "probably you saved the model using nn.DataParallel, which stores the model in module, and now you are trying to load it without DataParallel."

My fix is in the compress_classifer.py:
Change the logic:
is_parallel = not png_summary and args.summary != 'compute'  # For PNG summary, parallel graphs are illegible
into:
is_parallel = not (png_summary and args.summary != 'compute')  # For PNG summary, parallel graphs are illegible #Chong change the logic

Then everything works fine. 
But I am not sure the changed logic is what your original meaning. 
Can you help double check it?

Actually, before you push the commit of fix binary change, you will get the following error info, so it is more clear to find the root cause:

...
Loaded compression schedule from checkpoint (epoch 277)
=> loaded checkpoint '../ssl/checkpoints/checkpoint_trained_channel_regularized_resnet20_finetuned.pth.tar' (epoch 277)
Traceback (most recent call last):
  File "compress_classifier.py", line 499, in <module>
    main()
  File "compress_classifier.py", line 225, in main
    model, chkpt_file=args.resume)
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/apputils/checkpoint.py", line 120, in load_checkpoint
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetCifar:
        Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.running_mean", "bn1.running_var", "bn1.bias", "layer1.0.conv1.weight", "layer1.0.bn1.weight", "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.bn1.bias", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.0.bn2.bias", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.bn1.bias", "layer1.1.conv2.weight", "layer1.1.bn2.weight", "layer1.1.bn2.running_mean", "layer1.1.bn2.running_var", "layer1.1.bn2.bias", "layer1.2.conv1.weight", "layer1.2.bn1.weight", "layer1.2.bn1.running_mean", "layer1.2.bn1.running_var", "layer1.2.bn1.bias", "layer1.2.conv2.weight", "layer1.2.bn2.weight", "layer1.2.bn2.running_mean", "layer1.2.bn2.running_var", "layer1.2.bn2.bias", "layer2.0.conv1.weight", "layer2.0.bn1.weight", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.bn1.bias", "layer2.0.conv2.weight", "layer2.0.bn2.weight", "layer2.0.bn2.running_mean", "layer2.0.bn2.running_var", "layer2.0.bn2.bias", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer2.0.downsample.1.bias", "layer2.1.conv1.weight", "layer2.1.bn1.weight", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.bn1.bias", "layer2.1.conv2.weight", "layer2.1.bn2.weight", "layer2.1.bn2.running_mean", "layer2.1.bn2.running_var", "layer2.1.bn2.bias", "layer2.2.conv1.weight", "layer2.2.bn1.weight", "layer2.2.bn1.running_mean", "layer2.2.bn1.running_var", "layer2.2.bn1.bias", "layer2.2.conv2.weight", "layer2.2.bn2.weight", "layer2.2.bn2.running_mean", "layer2.2.bn2.running_var", "layer2.2.bn2.bias", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.running_mean", "layer3.0.bn1.running_var", "layer3.0.bn1.bias", "layer3.0.conv2.weight", "layer3.0.bn2.weight", "layer3.0.bn2.running_mean", "layer3.0.bn2.running_var", "layer3.0.bn2.bias", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var", "layer3.0.downsample.1.bias", "layer3.1.conv1.weight", "layer3.1.bn1.weight", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.bn1.bias", "layer3.1.conv2.weight", "layer3.1.bn2.weight", "layer3.1.bn2.running_mean", "layer3.1.bn2.running_var", "layer3.1.bn2.bias", "layer3.2.conv1.weight", "layer3.2.bn1.weight", "layer3.2.bn1.running_mean", "layer3.2.bn1.running_var", "layer3.2.bn1.bias", "layer3.2.conv2.weight", "layer3.2.bn2.weight", "layer3.2.bn2.running_mean", "layer3.2.bn2.running_var", "layer3.2.bn2.bias", "fc.weight", "fc.bias".
        Unexpected key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var", "module.layer1.0.conv1.weight", "module.layer1.0.bn1.weight", "module.layer1.0.bn1.bias", "module.layer1.0.bn1.running_mean", "module.layer1.0.bn1.running_var", "module.layer1.0.conv2.weight", "module.layer1.0.bn2.weight", "module.layer1.0.bn2.bias", "module.layer1.0.bn2.running_mean", "module.layer1.0.bn2.running_var", "module.layer1.1.conv1.weight", "module.layer1.1.bn1.weight", "module.layer1.1.bn1.bias", "module.layer1.1.bn1.running_mean", "module.layer1.1.bn1.running_var", "module.layer1.1.conv2.weight", "module.layer1.1.bn2.weight", "module.layer1.1.bn2.bias", "module.layer1.1.bn2.running_mean", "module.layer1.1.bn2.running_var", "module.layer1.2.conv1.weight", "module.layer1.2.bn1.weight", "module.layer1.2.bn1.bias", "module.layer1.2.bn1.running_mean", "module.layer1.2.bn1.running_var", "module.layer1.2.conv2.weight", "module.layer1.2.bn2.weight", "module.layer1.2.bn2.bias", "module.layer1.2.bn2.running_mean", "module.layer1.2.bn2.running_var", "module.layer2.0.conv1.weight", "module.layer2.0.bn1.weight", "module.layer2.0.bn1.bias", "module.layer2.0.bn1.running_mean", "module.layer2.0.bn1.running_var", "module.layer2.0.conv2.weight", "module.layer2.0.bn2.weight", "module.layer2.0.bn2.bias", "module.layer2.0.bn2.running_mean", "module.layer2.0.bn2.running_var", "module.layer2.0.downsample.0.weight", "module.layer2.0.downsample.1.weight", "module.layer2.0.downsample.1.bias", "module.layer2.0.downsample.1.running_mean", "module.layer2.0.downsample.1.running_var", "module.layer2.1.conv1.weight", "module.layer2.1.bn1.weight", "module.layer2.1.bn1.bias", "module.layer2.1.bn1.running_mean", "module.layer2.1.bn1.running_var", "module.layer2.1.conv2.weight", "module.layer2.1.bn2.weight", "module.layer2.1.bn2.bias", "module.layer2.1.bn2.running_mean", "module.layer2.1.bn2.running_var", "module.layer2.2.conv1.weight", "module.layer2.2.bn1.weight", "module.layer2.2.bn1.bias", "module.layer2.2.bn1.running_mean", "module.layer2.2.bn1.running_var", "module.layer2.2.conv2.weight", "module.layer2.2.bn2.weight", "module.layer2.2.bn2.bias", "module.layer2.2.bn2.running_mean", "module.layer2.2.bn2.running_var", "module.layer3.0.conv1.weight", "module.layer3.0.bn1.weight", "module.layer3.0.bn1.bias", "module.layer3.0.bn1.running_mean", "module.layer3.0.bn1.running_var", "module.layer3.0.conv2.weight", "module.layer3.0.bn2.weight", "module.layer3.0.bn2.bias", "module.layer3.0.bn2.running_mean", "module.layer3.0.bn2.running_var", "module.layer3.0.downsample.0.weight", "module.layer3.0.downsample.1.weight", "module.layer3.0.downsample.1.bias", "module.layer3.0.downsample.1.running_mean", "module.layer3.0.downsample.1.running_var", "module.layer3.1.conv1.weight", "module.layer3.1.bn1.weight", "module.layer3.1.bn1.bias", "module.layer3.1.bn1.running_mean", "module.layer3.1.bn1.running_var", "module.layer3.1.conv2.weight", "module.layer3.1.bn2.weight", "module.layer3.1.bn2.bias", "module.layer3.1.bn2.running_mean", "module.layer3.1.bn2.running_var", "module.layer3.2.conv1.weight", "module.layer3.2.bn1.weight", "module.layer3.2.bn1.bias", "module.layer3.2.bn1.running_mean", "module.layer3.2.bn1.running_var", "module.layer3.2.conv2.weight", "module.layer3.2.bn2.weight", "module.layer3.2.bn2.bias", "module.layer3.2.bn2.running_mean", "module.layer3.2.bn2.running_var", "module.fc.weight", "module.fc.bias".


Log file for this run: /home/chongyu/Chong_dxxz_Projects/Github/distiller/examples/classifier_compression/logs/2018.07.04-130333/2018.07.04-130333.log
Traceback (most recent call last):
  File "compress_classifier.py", line 503, in <module>
    raise e
  File "compress_classifier.py", line 499, in <module>
    main()
  File "compress_classifier.py", line 225, in main
    model, chkpt_file=args.resume)
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/apputils/checkpoint.py", line 120, in load_checkpoint
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/chongyu/Chong_dxxz_Projects/Github/distiller/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetCifar:
        Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.running_mean", "bn1.running_var", "bn1.bias", "layer1.0.conv1.weight", "layer1.0.bn1.weight", "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.bn1.bias", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.0.bn2.bias", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.bn1.bias", "layer1.1.conv2.weight", "layer1.1.bn2.weight", "layer1.1.bn2.running_mean", "layer1.1.bn2.running_var", "layer1.1.bn2.bias", "layer1.2.conv1.weight", "layer1.2.bn1.weight", "layer1.2.bn1.running_mean", "layer1.2.bn1.running_var", "layer1.2.bn1.bias", "layer1.2.conv2.weight", "layer1.2.bn2.weight", "layer1.2.bn2.running_mean", "layer1.2.bn2.running_var", "layer1.2.bn2.bias", "layer2.0.conv1.weight", "layer2.0.bn1.weight", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.bn1.bias", "layer2.0.conv2.weight", "layer2.0.bn2.weight", "layer2.0.bn2.running_mean", "layer2.0.bn2.running_var", "layer2.0.bn2.bias", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer2.0.downsample.1.bias", "layer2.1.conv1.weight", "layer2.1.bn1.weight", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.bn1.bias", "layer2.1.conv2.weight", "layer2.1.bn2.weight", "layer2.1.bn2.running_mean", "layer2.1.bn2.running_var", "layer2.1.bn2.bias", "layer2.2.conv1.weight", "layer2.2.bn1.weight", "layer2.2.bn1.running_mean", "layer2.2.bn1.running_var", "layer2.2.bn1.bias", "layer2.2.conv2.weight", "layer2.2.bn2.weight", "layer2.2.bn2.running_mean", "layer2.2.bn2.running_var", "layer2.2.bn2.bias", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.running_mean", "layer3.0.bn1.running_var", "layer3.0.bn1.bias", "layer3.0.conv2.weight", "layer3.0.bn2.weight", "layer3.0.bn2.running_mean", "layer3.0.bn2.running_var", "layer3.0.bn2.bias", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var", "layer3.0.downsample.1.bias", "layer3.1.conv1.weight", "layer3.1.bn1.weight", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.bn1.bias", "layer3.1.conv2.weight", "layer3.1.bn2.weight", "layer3.1.bn2.running_mean", "layer3.1.bn2.running_var", "layer3.1.bn2.bias", "layer3.2.conv1.weight", "layer3.2.bn1.weight", "layer3.2.bn1.running_mean", "layer3.2.bn1.running_var", "layer3.2.bn1.bias", "layer3.2.conv2.weight", "layer3.2.bn2.weight", "layer3.2.bn2.running_mean", "layer3.2.bn2.running_var", "layer3.2.bn2.bias", "fc.weight", "fc.bias".
        Unexpected key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var", "module.layer1.0.conv1.weight", "module.layer1.0.bn1.weight", "module.layer1.0.bn1.bias", "module.layer1.0.bn1.running_mean", "module.layer1.0.bn1.running_var", "module.layer1.0.conv2.weight", "module.layer1.0.bn2.weight", "module.layer1.0.bn2.bias", "module.layer1.0.bn2.running_mean", "module.layer1.0.bn2.running_var", "module.layer1.1.conv1.weight", "module.layer1.1.bn1.weight", "module.layer1.1.bn1.bias", "module.layer1.1.bn1.running_mean", "module.layer1.1.bn1.running_var", "module.layer1.1.conv2.weight", "module.layer1.1.bn2.weight", "module.layer1.1.bn2.bias", "module.layer1.1.bn2.running_mean", "module.layer1.1.bn2.running_var", "module.layer1.2.conv1.weight", "module.layer1.2.bn1.weight", "module.layer1.2.bn1.bias", "module.layer1.2.bn1.running_mean", "module.layer1.2.bn1.running_var", "module.layer1.2.conv2.weight", "module.layer1.2.bn2.weight", "module.layer1.2.bn2.bias", "module.layer1.2.bn2.running_mean", "module.layer1.2.bn2.running_var", "module.layer2.0.conv1.weight", "module.layer2.0.bn1.weight", "module.layer2.0.bn1.bias", "module.layer2.0.bn1.running_mean", "module.layer2.0.bn1.running_var", "module.layer2.0.conv2.weight", "module.layer2.0.bn2.weight", "module.layer2.0.bn2.bias", "module.layer2.0.bn2.running_mean", "module.layer2.0.bn2.running_var", "module.layer2.0.downsample.0.weight", "module.layer2.0.downsample.1.weight", "module.layer2.0.downsample.1.bias", "module.layer2.0.downsample.1.running_mean", "module.layer2.0.downsample.1.running_var", "module.layer2.1.conv1.weight", "module.layer2.1.bn1.weight", "module.layer2.1.bn1.bias", "module.layer2.1.bn1.running_mean", "module.layer2.1.bn1.running_var", "module.layer2.1.conv2.weight", "module.layer2.1.bn2.weight", "module.layer2.1.bn2.bias", "module.layer2.1.bn2.running_mean", "module.layer2.1.bn2.running_var", "module.layer2.2.conv1.weight", "module.layer2.2.bn1.weight", "module.layer2.2.bn1.bias", "module.layer2.2.bn1.running_mean", "module.layer2.2.bn1.running_var", "module.layer2.2.conv2.weight", "module.layer2.2.bn2.weight", "module.layer2.2.bn2.bias", "module.layer2.2.bn2.running_mean", "module.layer2.2.bn2.running_var", "module.layer3.0.conv1.weight", "module.layer3.0.bn1.weight", "module.layer3.0.bn1.bias", "module.layer3.0.bn1.running_mean", "module.layer3.0.bn1.running_var", "module.layer3.0.conv2.weight", "module.layer3.0.bn2.weight", "module.layer3.0.bn2.bias", "module.layer3.0.bn2.running_mean", "module.layer3.0.bn2.running_var", "module.layer3.0.downsample.0.weight", "module.layer3.0.downsample.1.weight", "module.layer3.0.downsample.1.bias", "module.layer3.0.downsample.1.running_mean", "module.layer3.0.downsample.1.running_var", "module.layer3.1.conv1.weight", "module.layer3.1.bn1.weight", "module.layer3.1.bn1.bias", "module.layer3.1.bn1.running_mean", "module.layer3.1.bn1.running_var", "module.layer3.1.conv2.weight", "module.layer3.1.bn2.weight", "module.layer3.1.bn2.bias", "module.layer3.1.bn2.running_mean", "module.layer3.1.bn2.running_var", "module.layer3.2.conv1.weight", "module.layer3.2.bn1.weight", "module.layer3.2.bn1.bias", "module.layer3.2.bn1.running_mean", "module.layer3.2.bn1.running_var", "module.layer3.2.conv2.weight", "module.layer3.2.bn2.weight", "module.layer3.2.bn2.bias", "module.layer3.2.bn2.running_mean", "module.layer3.2.bn2.running_var", "module.fc.weight", "module.fc.bias".

**Comment by nzmora** [comment]
Hi Chong,

I'm seeing a different problem and I'm wondering why I can't recreate your issue.
Can you please attach the log file of an execution, after you make your change?
```
is_parallel = not (png_summary and args.summary != 'compute')
```

In fact, you can change it to a simpler expression (I will explain the details of this logical expression, after I get to the bottom of this issue):
```
is_parallel = not png_summary
```
Thanks!

**Comment by nzmora** [comment]
Hi @ChongyuIntel,
Please try branch https://github.com/NervanaSystems/distiller/tree/fix_26.
It should fix the issue you see.

**Comment by dxxz** [comment]
Hi~~ @nzmora 
Have verified you new branch fix_26, now it works fine for "Getting parameter statistics of a sparsified model" example now. Do you have the plan to merge into the master branch ?

**Comment by nzmora** [comment]
@ChongyuIntel - yeah, I'll probably merge it today or tomorrow.

**Comment by nzmora** [comment]
Closing as a fix has been merged to 'master' a couple of days ago.

**Comment by nzmora** [comment]
Closing as a fix has been merged to 'master' a couple of days ago.
