### ISSUE TITLE
PACT training taking too long

### ISSUE THREAD

**Issue by kocchop** [NervanaSystems/distiller#260]
The quantization aware training with PACT quantizer is taking an unreasonably long time compared to training with full precision or with other quantizers. Any clue on why is this happening? In PACT, there is an extra parameter that we have to learn. But that is also taken care of by resending the whole model to CUDA after the compression scheduling.

Any kind of suggestions on how to speed up the training with PACT will be highly appreciated. TIA

**Comment by guyjacob** [comment]
Comparing PACT to DoReFa, it is about 1.8x-2x slower on my setup. Does that match what you're seeing?

As to why this is happening - while it's true that there's "only" one new parameter per layer, if you  compare the `backward` functions of `LinearQuantizeSTE` ([here](https://github.com/NervanaSystems/distiller/blob/4c16369057e5dde41d0ac5ee0dca1a8cc67ddc36/distiller/quantization/q_utils.py#L196) - which is used by DoReFa) and `ClippedLinearQuantizeSTE` ([here](https://github.com/NervanaSystems/distiller/blob/4c16369057e5dde41d0ac5ee0dca1a8cc67ddc36/distiller/quantization/clipped_linear.py#L44) - which is used by PACT), you can see that the latter does a non-trivial additional amount of tensor-arithmetic. My guess is that there are inefficiencies hiding in there. I'd have to dig in a bit more to give concrete advice and/or fix it.

**Comment by kocchop** [comment]
Yes, for cifar, its almost 2x slower. But for ImageNet, I would say its much slower than that. Any tweaks around it would certainly be great! Thanks

**Comment by blueardour** [comment]
hi, @kocchop and @guyjacob  Did you already get some result on small datasets such as cifar10/100 of the PACT or Dorefa-net?  Would you mind to share the accuracy?

**Comment by kocchop** [comment]
Hi, @guyjacob, @nzmora did you have a chance to look at the issue? It's taking days to train on Imagenet using pact. Any advice/suggestions are very much appreciated. Thanks

**Comment by guyjacob** [comment]
Not yet, unfortunately. I'll try to take a look at it next week. Can you give more details on what you're seeing? Which model, what's the HW setup?

**Comment by kocchop** [comment]
Hi @guyjacob , yes definitely. I was trying to train resnet50 on ImageNet dataset. I am using 4 NVIDIA Tesla V100 GPUs each having 32GBs as GPU memory. Also, the physical memory of the system is around ~336GB. The model is wrapped using the DataParallel, so I guess parallelization is not the issue. Typical training with 256 batch size for ~100 epochs takes around 2/2.5 days in current settings. After including PACT to it, it looks like training would take 10-11 days at least. Please let me know if I can help you out with any other details. Thanks a lot!

**Comment by kocchop** [comment]
@guyjacob @nzmora sorry to bother again. Did you get a chance to look at the issue? 
Thanks a lot!

**Comment by guyjacob** [comment]
Hi @kocchop. So sorry it took me so long to look into this!.
I opened a PR - #336. Please check it out, see if it improves things on your side. I did limited experiments on my side and it's ~2x faster now. There's a more detailed explanation in the PR.

And again, sorry for the very delayed response.

**Comment by kocchop** [comment]
Hi @guyjacob, thanks a lot!! It has actually improved significantly! Just to be sure that I have similar performance compared to your implementation, could you please share your training logs for cifar and ImageNet if possible?

Also, a slightly out of context question. If you could kindly answer to that, it'd be a great help. During the quantization aware training, we use "the simulated quantization" effect. In code, we actually quantize and then dequantize for that. Assume that, I have a trained model with it and I want to map it to a hardware like fpga with integer arithmatic. What could be a good way to do that? I am slightly worried about the scaling factor that we dequantize with. If could kindly shed some light in this regard, it'd be a great help.

Thanks a lot, again for making the implementation more efficient!
