### ISSUE TITLE
compressing  resnet18 by using  the method of pruning_filters_for_efficient_convnets

### ISSUE THREAD

**Issue by tongyutyr** [NervanaSystems/distiller#264]
hello, I am trying to pruning filters of resnet18 by using the method of  pruning_filters_for_efficient_convnets,but I don't konw how to write the yaml.How to set the initial lr and  the training epochs? can someone help me?

**Comment by nzmora** [comment]
Hi @tongyutyr,

You can look at the [YAML syntax documentation](https://nervanasystems.github.io/distiller/schedule.html) and examples [here](https://github.com/NervanaSystems/distiller/tree/master/examples/pruning_filters_for_efficient_convnets) and [here](https://github.com/NervanaSystems/distiller/blob/master/examples/agp-pruning/resnet18.schedule_agp.yaml) and [here](https://nervanasystems.github.io/distiller/model_zoo.html#pruning-filters-for-efficient-convnets).

Cheers
Neta
