### ISSUE TITLE
Is there any plan to add nonlinear quantization method in the future version of Post-train Quantization? 

### ISSUE THREAD

**Issue by zhepengfei** [NervanaSystems/distiller#271]
Hi, 

It is really a wonderful project that helps me a lot in the model compression. Thanks!!

As described in title, I want to know that is there any plan to add nonlinear quatization method in the future version since nonlinear method can acquire higher compression ratio? The weight sharing method introduced in "Song Han, Deep compression: compressing deep neural networks with pruning, trained quantization and Huffman coding, ICLR 2016" may be a good nonlinear quantization method.

Look forward to your reply. 
Thanks again!!

**Comment by levzlotnik** [comment]
Hi,

Sorry for the late response. Unfortunately, we're not planning on implementing non-linear quantization.
Closing this issue due to staleness.
