### ISSUE TITLE
FakeLinearQuantization can be only run on single GPU, when can such problem be solved?

### ISSUE THREAD

**Issue by tdzdog** [NervanaSystems/distiller#276]
I am using the FakeLinearQuantization and I find it can only be run on a single GPU. I am doing an experiment on Imagenet. This makes quantizing networks like ResNet too slow. I wonder when the problem can be solved?

**Comment by levzlotnik** [comment]
Hi @tdzdog,

This task is high priority for us, and I will start to work on it soon enough.

Cheers,
Lev

**Comment by levzlotnik** [comment]
Hi @tdzdog ,

We've enabled multi-gpu support for `FakeLinearQuantization` in #284.

Cheers,
Lev
