### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by haim-barad** [NervanaSystems/distiller#280]
In the page https://nervanasystems.github.io/distiller/usage.html, there is a link on the word "explanation" in the bullet "An explanation of the scheduler file format."

This link is pointing to https://nervanasystems.github.io/distiller/schedule/index.html and returns a 404.

**Comment by haim-barad** [comment]
The bullet right after that also has a broken link - the text "discussion" points to https://nervanasystems.github.io/distiller/model_zoo/index.html and returns a 404.

**Comment by nzmora** [comment]
Thanks @haim-barad,
We didn't notice that a new version of mkdocs changed some of the page links.
Hopefully I got them all.
Cheers,
Neta
