### ISSUE TITLE
Quantization-Aware Training, Can not get activation scale/zero_point param table, if net has no Relu op.

### ISSUE THREAD

**Issue by tianylijun** [NervanaSystems/distiller#287]
Can not get activation scale/zero_point param table, if Net has no 'Relu' op.  As activation quantization only happen on Relu. This will cause Conv layer accept fp32 input, and 8 bits Weights, no benefit for compute efficiency. So may be a FakeQuantizationWrapper layer needed for each conv layer but not only Relu, to do activation quantization work.
----------------------------------------------------------
class DorefaQuantizer(Quantizer):
...
self.replacement_factory[nn.ReLU] = relu_replace_fn <----

class PACTQuantizer(Quantizer):
...
self.replacement_factory[nn.ReLU] = relu_replace_fn <---

class QuantAwareTrainRangeLinearQuantizer(Quantizer):
...
self.replacement_factory[nn.ReLU] = self.activation_replace_fn <---

**Comment by guyjacob** [comment]
Hi @tianylijun 

A similar question was asked in #256, I encourage you to take a look over there. In short, by quantizing the activations of the ReLU (and not the convolution layer) we're making the assumption that they are fused. So there is no need to quantize the convolution outputs separately. There are other layer connectivity patterns which are not covered by the current implementation - we're working on it. Again, please take a look at #256 to understand more.

**Comment by vdgs** [comment]
Hi, Is convolution output quantization supported now?
