### ISSUE TITLE
Question about SSL

### ISSUE THREAD

**Issue by Bowenwu1** [NervanaSystems/distiller#289]
Recently I'm trying SSL Algo. And after reading your code about GroupLassoRegularizer.I found something weird.

https://github.com/NervanaSystems/distiller/blob/516ba418864a0d8ddfd39da94f75281d4a8c9527/distiller/regularization/group_regularizer.py#L56-L59

https://github.com/NervanaSystems/distiller/blob/516ba418864a0d8ddfd39da94f75281d4a8c9527/distiller/regularization/group_regularizer.py#L85-L92

The above code means that `lambda=threshold`, and I think this is weird, am I right?
Cheers!

**Comment by Bowenwu1** [comment]
hello @nzmora remember to read this. Thanks!
Cheers～

**Comment by nzmora** [comment]
Hi @Bowenwu1,

I can see why you would think this is a bug, or find it confusing - but the code is OK (and apparently needs more documentation ;-).
Thresholding is optional. I used it to create stability in the regularized coefficients: when they get small, they oscillate around zero (to the best of my recollection), as explained [here](https://github.com/NervanaSystems/distiller/blob/master/jupyter/L1-regularization.ipynb) for element-wise L1 regularization.  This is sometimes referred to as _soft-thresholding_ (or _group soft-thresholding_ in this case).  For example see section 4.2 in [this book](https://books.google.co.il/books?id=RpfJDQAAQBAJ&pg=PA124&lpg=PA124&dq=group+regularization+thresholding&source=bl&ots=XpQyFg3y71&sig=ACfU3U1niV2NAzxLk0A280B3fqpbqtFpKQ&hl=en&sa=X&ved=2ahUKEwiqqrT9hv7iAhUkNOwKHZQ0DeQQ6AEwD3oECAkQAQ#v=onepage&q=group%20regularization%20thresholding&f=false).
Cheers
Neta
