### ISSUE TITLE
Checkpoints for pruned models

### ISSUE THREAD

**Issue by shashichilappagari** [NervanaSystems/distiller#293]
Hi,
I work at a startup focused on building HW accelerators for ML inference. Our focus is to build HW that can provide latency improvements when using pruned networks. We have been using Distiller for a while now and have gotten very good results. Thanks for sharing this very important tool. We have not seen any checkpoints of pruned models posted on this repo. We were wondering if we can provide links  (on our own github repo) to others to download some pruned networks so that they can check the performance. 
Regards
Shashi

**Comment by nzmora** [comment]
Hi @shashichilappagari,

Yes, of course!  We will be very happy to do that, and maybe it will get some other people to contribute pruned models as well.  
I don't know where we will post these links (README, Wiki page, documentation pages, perhaps a link to the list from our README), but I think that besides the links, it will be useful to provide some metadata about the checkpoints: (1) accuracy performance; (2) YAML script; (3) command line; (4) compression rate; (5) if you think of anything else. 
Please send us the information either thru this issue, or by email (distiller@intel.com).
Thank you!
Neta

**Comment by shashichilappagari** [comment]
Neta,
Thanks for your suggestions. We have created a repository containing links to the pruned models. Please see this [link](https://github.com/DeGirum/pruned-models). As per your suggestion, we have included meta-data in the pruning scheduler yaml file. Along with the information you suggested, we added information regarding number of MACS and command line to generate quantization results in the yaml file. We also hope that this will encourage people to share their models. We especially want to see pruned and quantized models for   speech applications.
Regards
Shashi

**Comment by nzmora** [comment]
Hi Shashi,
I've added a link to your repo from our README, and I know of one graduate student from Brazil who already found your repo helpful.
Good luck and I hope to see you publish more pruned/quantized models ;-)
Neta
