### ISSUE TITLE
How to block prune?

### ISSUE THREAD

**Issue by zwang-asapp** [NervanaSystems/distiller#296]
Hi, thanks for this great repo! I'm wondering if there is a pruner that supports the block pruning technique mentioned in https://openreview.net/forum?id=HJaDJZ-0W? Can it be implemented with the StructurePruner?

**Comment by levzlotnik** [comment]
Hi @zwang-asapp ,
Yes we have block pruning - you can see it in this [schedule config yaml](https://github.com/NervanaSystems/distiller/blob/master/examples/agp-pruning/resnet50.schedule_agp.1x1x8-blocks.yaml)

Let us know if you have more questions :)
Lev
