### ISSUE TITLE
Quantization aware training about relu

### ISSUE THREAD

**Issue by dongzhen123** [NervanaSystems/distiller#297]
if there is a shared relu op,then after retrain we could only get the scale and zero point of relu once,not all relu?so what should I do?

**Comment by guyjacob** [comment]
Apologies for the late reply. The solution would be to un-share it. That is, if ReLU is called N times during `forward()`, make sure to have N instances of ReLU - one for each call. You'll need to modify the model code to achieve that.

For example, if you have a module that looks like this:
```python
class MyModule(nn.Module):
    def __init__(self):
        self.conv1 = nn.Conv2d(....)
        self.relu = nn.ReLU()
        self.conv2 = nn.Conv2d(....)

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.conv2(x)
        x = self.relu(x)
        return x
```

Then you should modify it like this:
```python
class MyModule(nn.Module):
    def __init__(self):
        self.conv1 = nn.Conv2d(....)
        self.relu1 = nn.ReLU()
        self.conv2 = nn.Conv2d(....)
        self.relu2 = nn.ReLU()

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.conv2(x)
        x = self.relu2(x)
        return x
```

**Comment by dongzhen123** [comment]
Thank you very much！

**Comment by dongzhen123** [comment]
> Apologies for the late reply. The solution would be to un-share it. That is, if ReLU is called N times during `forward()`, make sure to have N instances of ReLU - one for each call. You'll need to modify the model code to achieve that.
> 
> For example, if you have a module that looks like this:
> 
> ```python
> class MyModule(nn.Module):
>     def __init__(self):
>         self.conv1 = nn.Conv2d(....)
>         self.relu = nn.ReLU()
>         self.conv2 = nn.Conv2d(....)
> 
>     def forward(self, x):
>         x = self.conv1(x)
>         x = self.relu(x)
>         x = self.conv2(x)
>         x = self.relu(x)
>         return x
> ```
> 
> Then you should modify it like this:
> 
> ```python
> class MyModule(nn.Module):
>     def __init__(self):
>         self.conv1 = nn.Conv2d(....)
>         self.relu1 = nn.ReLU()
>         self.conv2 = nn.Conv2d(....)
>         self.relu2 = nn.ReLU()
> 
>     def forward(self, x):
>         x = self.conv1(x)
>         x = self.relu1(x)
>         x = self.conv2(x)
>         x = self.relu2(x)
>         return x
> ```



> Apologies for the late reply. The solution would be to un-share it. That is, if ReLU is called N times during `forward()`, make sure to have N instances of ReLU - one for each call. You'll need to modify the model code to achieve that.
> 
> For example, if you have a module that looks like this:
> 
> ```python
> class MyModule(nn.Module):
>     def __init__(self):
>         self.conv1 = nn.Conv2d(....)
>         self.relu = nn.ReLU()
>         self.conv2 = nn.Conv2d(....)
> 
>     def forward(self, x):
>         x = self.conv1(x)
>         x = self.relu(x)
>         x = self.conv2(x)
>         x = self.relu(x)
>         return x
> ```
> 
> Then you should modify it like this:
> 
> ```python
> class MyModule(nn.Module):
>     def __init__(self):
>         self.conv1 = nn.Conv2d(....)
>         self.relu1 = nn.ReLU()
>         self.conv2 = nn.Conv2d(....)
>         self.relu2 = nn.ReLU()
> 
>     def forward(self, x):
>         x = self.conv1(x)
>         x = self.relu1(x)
>         x = self.conv2(x)
>         x = self.relu2(x)
>         return x
> ```

Thank you very much
