### ISSUE TITLE
Error occured when trying AMC

### ISSUE THREAD

**Issue by Bowenwu1** [NervanaSystems/distiller#298]
```
ERROR: rl-coach 0.12.1 has requirement pytest>=3.8.2, but you'll have pytest 3.8.1 which is incompatible.
ERROR: distiller 0.4.0rc0 has requirement pytest==3.5.1, but you'll have pytest 3.8.1 which is incompatible.
```
Recently, I'm trying AMC Algo. And before that, I need to install `rl_coach`, and above error occured. I think you should have `pytest>=3.5.1` on you requirements.txt rather than `pytest==3.5.1`

**Comment by nzmora** [comment]
Hi @Bowenwu1,

I will be releasing a newer version of AMC in a couple of weeks.  The new version will perform much better than the version in the code base (which generates poor results), and will require a new version of Coach (not all of this code is publicly available yet).  I will provide new installation instructions with the new release.
My advice is to wait for a few weeks for the new code.

Thanks,
Neta
