### ISSUE TITLE
How to kernel prune?

### ISSUE THREAD

**Issue by dongzhen123** [NervanaSystems/distiller#301]
Hi, thanks for this great repo! I'm wondering if there is a pruner that supports the kernel pruning technique. Can it be implemented with the StructurePruner?

**Comment by nzmora** [comment]
Hi @dongzhen123,

We do not support kernel pruning, but it should be straight-forward to add.  It is similar to channel-pruning, except we don't "tie" the kernels together into a channel shape.
So, reshape a 4D tensor into 2D, with rows having the kernel elements (k*k coefficients) - so you have a matrix with shape (n_filters * n_channels, k*k).  For each row compute the L1-norm, to generate a 1D vector (len: n_filters * n_channels).  Sort this vector to determine the masking threshold, then mask, and finally expand the 1D mask to 4D mask (similar code exists for other structures).
See here: https://github.com/NervanaSystems/distiller/blob/6cd22e7dc62ba546ce54a000485a6b484671ac9e/distiller/pruning/ranked_structures_pruner.py#L110-L125

Good luck and let me know if you need help,
Neta
