### ISSUE TITLE
shortcut connection in AMC

### ISSUE THREAD

**Issue by zhengge** [NervanaSystems/distiller#305]
Hi,
I got an error `RuntimeError: The size of tensor a (13) must match the size of tensor b (16) at non-singleton dimension 1` when I use shortcut connection in the model.
The pruning channel of two layers are different.

**Comment by nzmora** [comment]
Hi @zhengge,

The AMC code in the `master` branch will be updated soon with a new and correct version.
Shortcut connections are always tricky when removing channels/filters and require special handling.
I'll discuss this issue when I commit the new AMC code.
Sorry for your troubles,
Neta

**Comment by zhengge** [comment]
Thanks for the response.

**Comment by HKLee2040** [comment]
@nzmora  Is the result of latest version same as Han's paper?

**Comment by nzmora** [comment]
Hi @HKLee2040 ,

You can now try the auto-compression [code](https://github.com/NervanaSystems/distiller/tree/master/examples/auto_compression) in 'master'.  
Cheers
Neta

**Comment by HKLee2040** [comment]
@nzmora 

It seems that only "--amc-rllib=random" can work, isn't it?
Did I miss anything?

python3 amc.py --arch=resnet20_cifar ../../../../data.cifar10 --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar --amc-protocol=mac-constrained --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=coach -j=1

**Comment by nzmora** [comment]
Hi @HKLee2040,

Sorry, I need to add an explanation of how to use the other RL libs.  I'll do that sometime next week.

Meanwhile, you can try using [MIT's HAN Lab's](https://github.com/mit-han-lab) DDPG agent.
Our AMC implementation is designed such that you can easily switch between RL libraries (i.e. different agent implementations).  The `--amc-rllib` argument instructs us which library to use.
For `--amc-rllib=coach` you need to install [coach](https://github.com/NervanaSystems/coach) in your Python virtual-env.  The "private" library, `--amc-rllib=private`, refers to HAN Lab's agent implementation.

Copy the DDPG files from [HAN Lab's github](https://github.com/mit-han-lab/amc-release/tree/master/lib) to `distiller/examples/auto_compression/amc/rl_libs/private/`.
It should plug and play, if I remember correctly.

Let me know if this helped you, and I'll use it to create the documentation.
Thanks!
Neta

**Comment by HKLee2040** [comment]
@nzmora 
Thanks for your explanation.

1. rllib = coach
    If I follow the instructions shown on the coach website, "RewardEwmaNormalizationFilter" is missed and got the following error message
  File "/media/walker/Data/work/distiller/examples/auto_compression/amc/rl_libs/coach/presets/ADC_DDPG.py", line 14, in <module>
    from rl_coach.filters.reward import RewardEwmaNormalizationFilter
ImportError: cannot import name 'RewardEwmaNormalizationFilter'

2. rllib = private
    It still needs to copy lib/memory.py and lib/utils.py from Han's github.
    And copy "train" function from amc_search.py into agent.py due to the following import in private_if.py
"    from examples.auto_compression.amc.rl_libs.private.agent import DDPG, train"
    It can work basically.  But the accuracy in search step is only around 74%.  Is it the same as your result?

python3 amc.py --arch=resnet20_cifar ../../../../data.cifar10 --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar --amc-protocol=mac-constrained --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=private -j=1

**Comment by nzmora** [comment]
Hi @HKLee2040 ,

For (1) you need to install the Coach 'master' branch.  Coach releases are issued every few months, and between official releases you can find the latest code in the 'master' branch.  Some features required for AMC are not yet in an official release.

Regarding (2) - thanks for the correction, I'll make note of it.
You can take a look at some of my experiments in [this notebook](https://github.com/NervanaSystems/distiller/blob/master/examples/auto_compression/amc/jupyter/amc_resnet20.ipynb).  I pasted one sample execution below.  You can see that the search Top1 accuracy reaches the upper 70s in this particular experiment.  I need to figure out how to share the logs of the experiments referred to in the notebook.  You can also load your own experiments to the notebook and see the learning process.

The [AMC worksheet notebook](https://github.com/NervanaSystems/distiller/blob/master/examples/auto_compression/amc/jupyter/amc_worksheet.ipynb) also has some interesting views of the learning process, including a cell to create an animation of the search

![image](https://user-images.githubusercontent.com/31280975/62840404-dec9c600-bca2-11e9-91a4-0b7c7c044f18.png)
![image](https://user-images.githubusercontent.com/31280975/62840471-30bf1b80-bca4-11e9-92ce-1fd8cd22d2c9.png)

**Comment by levzlotnik** [comment]
Hi,
Closing this due to staleness. Feel free to reopen if further questions arise.
