### ISSUE TITLE
Compress any given model

### ISSUE THREAD

**Issue by xingyueye** [NervanaSystems/distiller#312]
First thanks for your great work and sharing!
I have a question, if distiller is able to compress any given model. What should I do if i need to compress a new model using distiller. Especially for pruning part, such as thinning , what changes do I need to make. Because as far as I know, the implementation of thinning is more relevant to the structure of each model.

**Comment by nzmora** [comment]
Hi @xingyueye,

Distiller is not able to compress any given model.  There are too many types of networks for different  tasks and there is no "one-size-fits-all" method for compression.  We've put most of our efforts toward compression image-classifiers (CNNs), but we also have examples of models from other domains (e.g. language model).  Thinning changes the structure of a model, so it is especially sensitive to details of layers and their dependencies.  We add support for features that we find interesting and important, so if you have specific requests, please let us know.
Cheers,
Neta

**Comment by shixinlishixinli** [comment]
hello

i want to prune the centernet. Can I speed up the inference with agp-pruning? if yes, what should i do ?

best
lisa shi
