### ISSUE TITLE
os.sched_getaffinity(0) not available on macOS, others

### ISSUE THREAD

**Issue by rotx-maxim** [NervanaSystems/distiller#323]
`distiller/apputils/execution_env.py` logs the number of CPUs using `os.sched_getaffinity(0)`. This call is not available on macOS (and probably others, such as Windows). Since this is only a log file entry, functionality is unaffected without it.

Perhaps this could fall back to `multiprocessing.cpu_count()` on platforms that don't have it (even though this is not exactly the same), or just not print at all.

**Comment by guyjacob** [comment]
This is a small change which I don't mind making. But please note that we only support and test Distiller on Ubuntu. So even with this fix, you may encounter other issues on macOS, which we may not be able to help with and/or fix in the code.

I'll push a commit soon.

**Comment by guyjacob** [comment]
Pushed the fix.
