### ISSUE TITLE
PyTorch example

### ISSUE THREAD

**Issue by arijit17** [NervanaSystems/distiller#324]
I’m new to Distiller but familiar with PyTorch.
Do you have some Distiller examples with PyTorch?
This example (https://github.com/NervanaSystems/distiller/wiki/Tutorial:-Using-Distiller-to-prune-a-PyTorch-language-model) seems to be unavailable?

**Comment by levzlotnik** [comment]
Hi @arijit17 ,

Distiller is written almost entirely in PyTorch, so all of our examples are on PyTorch models.
The link in the wiki page is broken, here's the updated link to the tutorial:  
https://nervanasystems.github.io/distiller/tutorial-lang_model.html 

All the tutorials and docs are in https://nervanasystems.github.io/distiller.

Lev

**Comment by nzmora** [comment]
Hi @arijit17 
Adding to what @levzlotnik wrote, [this](https://github.com/NervanaSystems/distiller/blob/43548debc7e8aea743889278d0f1076eeaadc67e/examples/classifier_compression/compress_classifier.py) is our main example of using Distiller to compress PyTorch image classifiers.
Cheers
Neta

**Comment by arijit17** [comment]
Thank you @nzmora and @levzlotnik - next 3 months I’m gonna play heavily with Distiller.
