### ISSUE TITLE
Google Colab INstallation issue

### ISSUE THREAD

**Issue by karanchahal** [NervanaSystems/distiller#329]
Hello,

When I git clone the distiller repo into google colab and run ```pip3 install -e .``` ,  the runtime crashes and can't reconnect thereafter. I need to reset the runtime for it to run.

Can you update the build script so that it runs with Google colab ? 

The following warning comes when I install on a Google colab instance, maybe it's something to do with this ?

```
WARNING: The following packages were previously imported in this runtime:
  [ipywidgets,prompt_toolkit]
You must restart the runtime in order to use newly installed versions.
```

**Comment by nzmora** [comment]
Hi @karanchahal,

We currently don't use Colab in our work flow.  We'd be happy if you can debug this and share the solution with us!

Cheers,
Neta

**Comment by karanchahal** [comment]
Hey, the fix is very simple. One just needs to remove the ipywidgets==7.4.2 line from requirements.txt. Should I raise a PR that adds a simple line in the installation readme ? 

Best,
Karan

**Comment by nzmora** [comment]
Hi @karanchahal ,

What version of ipwidgets does Colab use/require?  I do not want to use a non-versioned package.
Thanks
Neta

**Comment by karanchahal** [comment]
Hey @nzmora , They're using the 7.5.0 version, but that could change. Maybe we could do ipywidgets>=7.4.2 and skip the hard installation requirement?

**Comment by nathanhubens** [comment]
Hey @karanchahal, does removing the ipywidget line in the requirements really work for you ? I still have:
```
WARNING: The following packages were previously imported in this runtime:
  [prompt_toolkit]
You must restart the runtime in order to use newly installed versions.
```

And when restarting, the colab session breaks.

Thanks, 

Nathan

**Comment by karanchahal** [comment]
Hmm the only difference is I didnt restart and just wrote import distiller
on the next cell. It worked. Let me know if you still got an error.

**Comment by nathanhubens** [comment]
@karanchahal Works fine now, thanks !
