### ISSUE TITLE
Issues with distiller test accuracy

### ISSUE THREAD

**Issue by kspoon1** [NervanaSystems/distiller#334]
I trained and compressed a simplenet_cifar model using distiller and received a top1 score of 81.710. I would like to use this model within my existing codebase, so I would like to test it outside of distiller.

When I test the model outside of distiller I receive a test accuracy of 0.675. This is with the same dataset, same architecture, same parameters, etc. I checked distiller's evaluation by running:

`python compress_classifier.py -a simplenet_cifar --resume-from='checkpoint.pth.tar' data.cifar10 --evaluate`

This gives 81.710, as expected. I test using the standard pytorch test code, but I don't know why it gives such a low accuracy. Is there something in distiller evaluation that is different from pytorch test code? 

I would really appreciate any help on this! Been stuck for awhile.

**Comment by nzmora** [comment]
Hi @kspoon1,

Distiller checkpoints are pytorch model checkpoints that should perform the same outside Distiller, as they perform within Distiller (assuming the same datasets, pre-processing, networks, etc.).
Can you share the problematic checkpoint?  For example, you can load it to Google Drive and share the link with us.  We can delete the link once we get the checkpoint.
An alternative is to share with us the code with which you test the checkpoint.

Is the test accuracy that you get outside Distiller 0.675% or 67.5%?
Thanks
Neta

**Comment by kspoon1** [comment]
[Here](https://drive.google.com/file/d/1onQSTkvX_ozKYItS3T_kcDukCLoIQJDx/view?usp=sharing) is the checkpoint. I also changed SimpleNet slightly:

`Simplenet(`
`  (conv1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1))`
`  (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))`
`  (conv3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))`
`  (fc1): Linear(in_features=1600, out_features=10, bias=True)`
`)`

And the test accuracy is around 67.5% instead of around 82%. 

Thanks! If you still need it I can also share the test code.

**Comment by kspoon1** [comment]
Fixed! Was an issue with data loading.
