### ISSUE TITLE
Poll: minimum Python version

### ISSUE THREAD

**Issue by nzmora** [NervanaSystems/distiller#335]
We're taking a poll on how you feel about making Python 3.6 or 3.7 a mandatory prerequisite.
Currently we require Python 3.5.

<b>Press on one of the progress bars below to register your vote :-)</b>

[![](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.5)](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.5/vote)
[![](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.6)](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.6/vote)
[![](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.7)](https://api.gh-polls.com/poll/01DGT1RT09WANKJMXQTW02SB3N/Python%203.7/vote)

**Comment by barrh** [comment]
Python 3.6:
* According to Pypi, Py3.6 is the 2nd most popular Python release among torch users, in the past 7 months. 2.7 is still the first. [REF](https://pypistats.org/packages/torch)
* Some of Distiller dependencies don't support <3.6 Python releases in their recent (and future) releases. e.g. matplotlib

**Comment by nzmora** [comment]
I tend to give more weight to the 'python 3.5 bunch', simply because these people might not be able to upgrade to a higher version of Python.

**Is this a real concern for anyone?**
