### ISSUE TITLE
How to use multi agent in AMC？

### ISSUE THREAD

**Issue by zhengge** [NervanaSystems/distiller#349]
Hi，
I do not know how to use multi agent in AMC.
In `AutoML for Model Compression (AMC): Trials and Tribulations`, it is not mentioned.

Thanks!

**Comment by nzmora** [comment]
HI @zhengge ,

I just deleted the wiki page you referred to above: it contained misleading information regarding our previous AMC implementation.  Please have a look [here](https://github.com/NervanaSystems/distiller/blob/master/examples/auto_compression/amc/README.md) for information about the correct AMC implementation (documentation on installation is still wip).
*However* I didn't understand what you mean by "multi agent in AMC".  Can you elaborate?

Thanks,
Neta

**Comment by zhengge** [comment]
Hi @nzmora ,
Thanks for the response.
Sorry, I mean "asynchronously execute multiple agents in parallel", like A3C.

**Comment by levzlotnik** [comment]
Hi,

Closing this issue due to staleness.
