### ISSUE TITLE
RuntimeError: Inplace operation detected

### ISSUE THREAD

**Issue by le8888e** [NervanaSystems/distiller#351]
Hello,
        Very impressive work! Thanks!
         When I do Post-Training Quantization on my self-defined model which contains a squeeze-and-excitation module, on the step of generate .yaml file, I got a problem:

raise RuntimeError('Inplace operation detected, meaning inputs stats are overridden by output stats. 'RuntimeError: Inplace operation detected, meaning inputs stats are overridden by output stats. You can either disable this check or make sure no in-place operations occur. See QuantCalibrationStatsCollector class documentation for more info.

That occurs because squeeze-and-excitation module has inplace operation.  Do you know how to disable this check? Thanks a lot.

Sincerely

**Comment by le8888e** [comment]
By the way, when define forward(), Does the Variable of different step of output has to be named differently? Or there will be Inplace operation detected error so that static result .yaml can not be generated? Thank you.

**Comment by nzmora** [comment]
Hi @le8888e,

The explanation for your first question is [here](https://github.com/NervanaSystems/distiller/blob/6782ccaeae0c02b542c4050d55abc585e34dd1bd/distiller/data_loggers/collector.py#L335-L375): 
> If a certain layer operates in-place, that layer's input stats will be overwritten by its output stats.  The collector can, optionally, check for such cases at runtime. In addition, a simple mechanism to disable inplace operations in the model can be used. See arguments details below."

You can edit the squeeze-and-excitation module to configure this operation not to be in-place.

I didn't understand your second question.

Cheers
Neta

**Comment by guyjacob** [comment]
To disable the check, pass `inplace_runtime_check=False` to the __init__ function of `QuantCalibrationStatsCollector`. Note that if the inplace operation is coming from a module with a `inplace` attribute (e.g. `self.relu = nn.ReLU(inplace=True)`), then the collector can automatically detect those. In that case, pass `disable_inplace_attrs=True` to the collector's __init__function.
The link @nzmora posted in the previous comment will take you to the collector's class documentation where you can see more details.

Regarding your second question - if I understand it correctly, you're asking if there is any restriction on the Python variable names in terms of in-place operations detection. Am I right? In that case, the answer is that there's no restriction. Variable names are not related.
