### ISSUE TITLE
Thinning doesn't work on ConvTranspose2d

### ISSUE THREAD

**Issue by trougnouf** [NervanaSystems/distiller#354]
Thinning doesn't work on ConvTranspose2d. I tried replacing the instances of 
`assert isinstance(layer, torch.nn.modules.Conv2d)`
by 
```
def isconv2d(layer):
    return isinstance(layer, torch.nn.modules.Conv2d) or isinstance(layer, torch.nn.modules.ConvTranspose2d)
assert isconv2d(layers[layer_name])
```
in thinning.py, but that's not enough as the input channels of ConvTranspose2d remain unchanged whether the previous layer was a ConvTranspose2d or a Conv2d.

**Comment by nzmora** [comment]
Hi @trougnouf 
We have not integrated support for `torch.nn.modules.ConvTranspose2d` as of yet.
Cheers
Neta

**Comment by levzlotnik** [comment]
Hi,
Closing due to staleness.
