### ISSUE TITLE
Structure pruning error

### ISSUE THREAD

**Issue by tom2002965** [NervanaSystems/distiller#363]
Hi,

When I try yo use [this yaml](https://github.com/NervanaSystems/distiller/blob/master/examples/network_trimming/resnet50.filters.activation_apoz_agp.yaml) to thinning my resnet imported from torchvision(I have edit weight name), I got some error.
It told me below : 
`TypeError: rank_and_prune_filters() takes from 6 to 7 positional arguments but 8 were given
`
I have checked the source code but can't solve the problem.

Final, I tried the command **compress_classify.py**, it also raise the error!
![0823](https://imgur.com/zIQx722.jpg)

Thanks

**Comment by nzmora** [comment]
Thanks @tom2002965,
I've fixed the issue.  Please let me know if there are other problems.
Thanks
Neta
