### ISSUE TITLE
channel pruning for ssd detection model

### ISSUE THREAD

**Issue by Cathynuo** [NervanaSystems/distiller#366]
Hi! I got a mobilenet-ssd pytorch model which is for object detection but it seems there are only classification samples. I wonder is there anyone could share the detailed tutorial about adding object detection model in distiller please?
Thank you very much!

**Comment by levzlotnik** [comment]
Hi @Cathynuo ,

I am working on adding an object detection sample with distiller (specifically - FastRCNN/MaskRCNN).
Pruning for object detection model would be similar to any other kind of model (classifiers and even RNNs), since you only prune weights you don't even have to make changes to the model.  

For more details you could look at my [PR](https://github.com/NervanaSystems/distiller/tree/object_detection), I have added a YAML config file for pruning blocks in MaskRCNN w/ ResNet50.  
Let me know if you have more questions.

Lev

**Comment by zhyj3038** [comment]
@levzlotnik  Hi, after the agp work, the maskrcnn's mAP drops significantly ? so excited for your maskrnn work!!!!

**Comment by cvJie** [comment]
> @levzlotnik Hi, after the agp work, the maskrcnn's mAP drops significantly ? so excited for your maskrnn work!!!!

Me ,too

**Comment by andyqian2015** [comment]
＠levzlotnik　If just change the weights but the model is the same as before, how the gpu memory using drop ? thx

**Comment by Iris0925** [comment]
> 
> 
> Hi @Cathynuo ,
> 
> I am working on adding an object detection sample with distiller (specifically - FastRCNN/MaskRCNN).
> Pruning for object detection model would be similar to any other kind of model (classifiers and even RNNs), since you only prune weights you don't even have to make changes to the model.
> 
> For more details you could look at my [PR](https://github.com/NervanaSystems/distiller/blob/object_detection/examples/object_detection_compression/train.py), I have added a [YAML config file](https://github.com/NervanaSystems/distiller/blob/object_detection/examples/object_detection_compression/maskrcnn.scheduler_agp_blocks_1x1x1x4.yaml) for pruning blocks in MaskRCNN w/ ResNet50.
> Let me know if you have more questions.
> 
> Lev

@levzlotnik If I want to prune channels/filters of an object detection model, what should I do?
Thank you very much!

**Comment by levzlotnik** [comment]
Hi, 
Sorry for the late response..


> @levzlotnik Hi, after the agp work, the maskrcnn's mAP drops significantly ? so excited for your maskrnn work!!!!

Please refer to the example `examples/object_detection_compression`, you can see all the results for maskrcnn. tl;dr - with 85.5% sparsity the mAP drops slightly, and from my experience for 70% sparsity mAP doesn't drop at all.



> ＠levzlotnik　If just change the weights but the model is the same as before, how the gpu memory using drop ? thx

As was stated in [FAQ](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)), we only apply a zero mask and so the GPU memory doesn't drop using distiller. To allow sparse calculations - use specialized hardware, or use thinning if you've pruned channels/filters, which does reduce the gpu memory and runtime.



> > Hi @Cathynuo ,
> > I am working on adding an object detection sample with distiller (specifically - FastRCNN/MaskRCNN).
> > Pruning for object detection model would be similar to any other kind of model (classifiers and even RNNs), since you only prune weights you don't even have to make changes to the model.
> > For more details you could look at my [PR](https://github.com/NervanaSystems/distiller/blob/object_detection/examples/object_detection_compression/train.py), I have added a [YAML config file](https://github.com/NervanaSystems/distiller/blob/object_detection/examples/object_detection_compression/maskrcnn.scheduler_agp_blocks_1x1x1x4.yaml) for pruning blocks in MaskRCNN w/ ResNet50.
> > Let me know if you have more questions.
> > Lev
> 
> @levzlotnik If I want to prune channels/filters of an object detection model, what should I do?
> Thank you very much!

As noted before, you should first prune the channels/filters using a structured pruner, and then thin the model using thinning.
