### ISSUE TITLE
Restoring from a checkpoint failed. Missing optimizer error.

### ISSUE THREAD

**Issue by wfong443** [NervanaSystems/distiller#367]
Using DorefaQuantizer, but believe problem existing for other quantizers in clipped_linear.py.
Issue seems to be that the optimizer must be loaded first before a call to line 223 that requires the optimizer. Currently load optimizer happens near the end at line 247 in the function load_checkpoint.

Here is the trace dump.

Log file for this run: classifier_compression/logs/2019.08.27-131259/2019.08.27-131259.log
Traceback (most recent call last):
  File "compress_classifier.py", line 204, in <module>
    main()
  File "compress_classifier.py", line 73, in main
    app = ClassifierCompressorSampleApp(args, script_dir=os.path.dirname(__file__))
  File "compress_classifier.py", line 162, in __init__
    super().__init__(args, script_dir)
  File “\distiller/apputils/image_classifier.py", line 68, in __init__
    self.start_epoch, self.ending_epoch) = _init_learner(args)
  File “distiller/apputils/image_classifier.py", line 377, in _init_learner
    model, args.resumed_checkpoint_path, model_device=args.device)
  File "distiller/apputils/checkpoint.py", line 223, in load_checkpoint
    quantizer = qmd['type'](model, **qmd['params'])
TypeError: __init__() missing 1 required positional argument: 'optimizer'

**Comment by levzlotnik** [comment]
Hi @wfong443 ,

This is a known bug which we are fixing in #309 , soon it will be pushed and you'll be able to resume any Quantization-Aware Training compression scheduler.

Thanks,
Lev
