### ISSUE TITLE
Thresholding 4D Tensors

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#37]
In https://github.com/NervanaSystems/distiller/blob/c2a429374f424ab357f55fd89d9d0d9289a570fe/distiller/thresholding.py#L90 Is the comparison operation Reversed?

My understanding is that, If the mean or the max is greater than the threshold, We would expect to have zeros in the mask.

**Comment by nzmora** [comment]
Hi Vinu,

This is an interesting question, but the short answer is: no, the comparison operation is not reversed.  Following your question I've read thru the code again, and I think more documentation about the mask would help.

[This](https://github.com/NervanaSystems/distiller/blob/master/distiller/scheduler.py#L36:L53) is the code that uses the mask and you can see here:  
https://github.com/NervanaSystems/distiller/blob/master/distiller/scheduler.py#L50

We element-wise multiply (in-place) the parameters tensor by the (binary) mask tensor.  This effectively removes (zeroes) coefficients that have a corresponding zero in same index in the mask, and leaves the other coefficients untouched.  
When we threshold, for example in:
https://github.com/NervanaSystems/distiller/blob/master/distiller/thresholding.py#L122
We use (torch.gt)[https://pytorch.org/docs/stable/torch.html#torch.gt] which returns 
> A torch.ByteTensor containing a 1 at each location where comparison is true  

https://github.com/NervanaSystems/distiller/blob/master/distiller/thresholding.py#L90:L91 can return a tensor of all 1's, or a `None` (which is what I chose to do).
I hope this clears things up.

**Comment by vinutah** [comment]
Thanks!
