### ISSUE TITLE
May I get inference speed up if I quantize the model then export to ONNX then to caffe2

### ISSUE THREAD

**Issue by WilliamZhaoz** [NervanaSystems/distiller#379]
I quantized the example model, then I test inference time, I found that inference time increased. So I search the question, I got 
https://github.com/NervanaSystems/distiller/issues/238 and 
https://github.com/NervanaSystems/distiller/issues/159
as you mentioned 
"
We do, however, plan to support exporting of quantized models using ONNX, once quantization is published as part of the standard. Then you'll be able to export a model quantized in Distiller and run it on a framework that supports actual 8-bit execution on CPU/GPU
"
I wonder if I can, now, quantize my model then export to ONNX, then to caffe2(you said caffe2 support 8bit),  in this way, I can get inference speed up?
Thank you.

**Comment by levzlotnik** [comment]
Hi @WilliamZhaoz ,

At the moment we don't support exporting quantized models to onnx, because our quantization is simulated through additional operations.
It's still in the plans, but we aren't there yet at the moment.

Lev

**Comment by WilliamZhaoz** [comment]
thank you levzlotnik,
I am sorry, I have another question, is the pruning in distiller also simulated ? Can I get inference speed up if I pruning my model using distiller and then inference it? If not, how can I get inference speed up with the help of distiller.
Thank you.

**Comment by levzlotnik** [comment]
Hi @WilliamZhaoz ,

The pruning is not simulated, i.e. the weights are actually hard-zeroed. To get an inference speed up, you'll have to use a hardware that benefits from weight sparsity. Distiller provides a wide range of pruners that can help you with sparsifying either fine grained (per element), blocks, columns and up to whole channels and filters. 
When you save the checkpoint, the fine-tuned weights are saved along with masks (part of the `compression_sched` state dict) which you can later use to apply onto the weights and get the final sparse weights.

Lev

**Comment by WilliamZhaoz** [comment]
I am excited that pruning is not simulated, thank you Lev.
BTW, I want to prune my own model, I'd like to know where I can get a detailed instruction on how to prune my own model, what I need to do on my model.

Thanks,
Zhiyuan.

**Comment by nzmora** [comment]
Hi @WilliamZhaoz,

With regard to your earlier questions, we have more details in [Distiller's FAQ](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)).

If you have an image-classification model, that uses MNIST/CIFAR10/ImageNet, then setting up pruning of your own model is now easier.  I added a way to register your model so that after registering it, you can use it like any other model.  Check the code and let me know if it answers your question: https://github.com/NervanaSystems/distiller/blob/master/jupyter/tutorial__adding_new_model.ipynb

Cheers,
Neta

**Comment by WilliamZhaoz** [comment]
Thanks Neta!
I appreciate your work!
Now I want to prune my own model, but not a image-classification model, are
there some documents I can refer? Thank you!

Neta Zmora <notifications@github.com> 于2019年9月23日周一 下午8:13写道：

**Comment by levzlotnik** [comment]
Hi @WilliamZhaoz ,
Sorry for the late response.  
About pruning a non image-classification model - we have several examples of doing so, refer to our examples and docs please.

Closing this issue due to staleness and it seems resolved.
