### ISSUE TITLE
Quantize a quantize-aware trained model?

### ISSUE THREAD

**Issue by yifan-you-37** [NervanaSystems/distiller#380]
If we have a model that's quantize-aware trained by some custom code, is it possible to perform post-train quantization using distiller?

**Comment by tom2002965** [comment]
Hi,

Due to [this page](https://nervanasystems.github.io/distiller/algo_quantization.html)

> Note that converting from a quantization-aware training model to a post-training quantization model is not yet supported. Such a conversion will use the activation ranges tracked during training, so additional offline or online calculation of quantization parameters will not be required.

I think it can't convert to post-train quantization.
Hope to help you, thanks!
