### ISSUE TITLE
Sensitivity Analysis for GAN

### ISSUE THREAD

**Issue by simonplain** [NervanaSystems/distiller#384]
I'm getting started with Distiller and attempting to do a sensitivity analysis of a GAN using a checkpoint of a Generator.  Working through it I ran into a check in sensitivity.py:
```
if model.state_dict()[param_name].dim() not in [2,4]:
            continue
```

The dimensions for the model I'm using are always 1 and 3, never 2 or 4 so no sensitivity analysis is done.
Is there something about how my model is set up which would cause this?  Could you explain this limitation?

**Comment by nzmora** [comment]
Hi @simonplain ,

When I wrote the sensitivity analysis code I was thinking of weight-tensors belonging to nn.Linear modules (2D tensors) or nn.Conv2D (4D tensors) and the test there is to make sure that we ignore other tensors (e.g 1D bias).
For element-wise (fine-grained) pruning-sensitivity analysis you can safely remove this check https://github.com/NervanaSystems/distiller/blob/7f78b22ec5a1d03a5ae6fdcad1ba60b64ce196cc/distiller/sensitivity.py#L74-L75 but you must make sure that `net_params` or (`which_params` - they are the same variable) contains only tensors whose pruning-sensitivity you want to test:

https://github.com/NervanaSystems/distiller/blob/f312e0921bae75c3d88a619b6e985e2f25d18b2a/examples/classifier_compression/compress_classifier.py#L183-L188

Cheers,
Neta

**Comment by simonplain** [comment]
Thanks, that's helping make progress.
