### ISSUE TITLE
Hi,how to load student model with knowledge distiller?

### ISSUE THREAD

**Issue by cvJie** [NervanaSystems/distiller#389]
I run this command:
  python3 compress_classifier.py --arch simplenet_cifar ../../../data.cifar10 -p 30 -j=1 --lr=0.01 --kd-teacher simplenet_cifar --kd-resume checkpoint.pth.tar --kd-temp 5.0 --kd-dw 0.7 --kd-sw 0.3

and but here havn't  assign any student model?
so ,i don’t know what the student model ?
Please give me some advices?

**Comment by tom2002965** [comment]
Hello,
If I have no mistake, I think "--arch" implied the "student model".
And "--kd-teacher" implied "teacher model".
They train on the same dataset. 

Thanks!

**Comment by cvJie** [comment]
> Hello,
> If I have no mistake, I think "--arch" implied the "student model".
> And "--kd-teacher" implied "teacher model".
> They train on the same dataset.
> 
> Thanks!

thanks. Maybe you right
