### ISSUE TITLE
GroupThresholdMixin for Column Pruning

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#39]
In https://github.com/NervanaSystems/distiller/blob/c2a429374f424ab357f55fd89d9d0d9289a570fe/distiller/thresholding.py#L124 there is an unconditional reduction in case `threshold_criteria == Mean_Abs` and unconditional Max finding in case `threshold_criteria == max` along `dim =1` . Now if the `group_type == Cols` then `dim=0` will be required ?

**Comment by nzmora** [comment]
@vinutah - thanks for catching this bug!
