### ISSUE TITLE
how to define the weights in yams?channel pruning

### ISSUE THREAD

**Issue by cvJie** [NervanaSystems/distiller#390]
Hi,
    I have found this file:
examples/pruning_filters_for_efficient_convnets/resnet56_cifar_channel_rank.yaml 

But I can’t understand why to assign these weights in filter_prunner_number,and why the desired_sparsity is 0.7, such as:
filter_pruner_70:
****************
desired_sparsity: 0.7
    weights: [
      module.layer1.1.conv1.weight,
      module.layer1.0.conv1.weight,
      module.layer1.2.conv1.weight,
      module.layer1.3.conv1.weight,
      module.layer1.4.conv1.weight,
      module.layer1.5.conv1.weight,
      module.layer1.6.conv1.weight,
      module.layer1.7.conv1.weight,
      module.layer1.8.conv1.weight,
      module.layer2.0.conv1.weight,
      module.layer2.0.downsample.0.weight
      ]

Can you give me some advice?

Now ,i want to prune own model, how to assign these param?

**Comment by andyqian2015** [comment]
＠cvJie, there is a question to wonder ? when compress process has done, how to save the prune model and how to use the prune weights? thx

**Comment by asti205** [comment]
@cvJie:
The list "weights" contains the layers that shall be pruned. So for your own model, you would need to get all the layer names and decide which ones you want to prune.

Then there is the next thing: Which sparsity do you want for those layers, meaning the relative number of zeros in those weights? For some layers, especially the layers at the beginning, it makes more sense to prune with a lower sparsity.
So after all you decide, which sparsity you want for which layers, and then create a pruner for each sparsity, e.g. filter_pruner_70 for a sparsity of 70%, and filter_pruner_30 for 30%. And in each of these pruners, you add the layers where you want the declared sparsity.

**Comment by Allhailankurgupta** [comment]
How to define your algorithm based on which you can prune

**Comment by nzmora** [comment]
Hi @Allhailankurgupta,
The full specification of the compression schedule specification (YAML format) is provided in our [documentation](https://nervanasystems.github.io/distiller/schedule.html).
Cheers,
Neta
