### ISSUE TITLE
Is there a quick way to to get the quantized weights after post-training quantization

### ISSUE THREAD

**Issue by rdoshi96** [NervanaSystems/distiller#392]
I used post-training quantization on a neural network architecture with LSTMs and I have a quantizer.model that has the scale-factors and activations for each layer. However, I want the actual quantized weights after running post-training quantization. Does distiller have an automated way to get these weights?

**Comment by nzmora** [comment]
Hi @rdoshi96 ,

When you execute `compress_classifier.py` with `--qe` (or `--quantize-eval`), a checkpoint with the quantized weights is generated.

you can see this here :https://github.com/NervanaSystems/distiller/blob/0036011d2141c665ae5152283dcd24ae9a08fa34/distiller/apputils/image_classifier.py#L833-L837

and here:https://github.com/NervanaSystems/distiller/blob/534072d826b304e70a4cf4ebe61ab8407cd0b3d8/distiller/quantization/range_linear.py#L198-L200

Cheers,
Neta

**Comment by rdoshi96** [comment]
Hi @nzmora ,

Thank you for your reply. This is the python code I use to get my quantized model:

`model = Transducer(config.model)

    checkpoint = torch.load(config.training.load_model)
    model.encoder.load_state_dict(checkpoint['encoder'])
    model.decoder.load_state_dict(checkpoint['decoder'])
    model.joint.load_state_dict(checkpoint['joint'])
    from distiller.modules import convert_model_to_distiller_lstm
    model = convert_model_to_distiller_lstm(model)
    print(model)
    import os
    from distiller.data_loggers import QuantCalibrationStatsCollector, collector_context

    stats_file = './model_stats.yaml'
    if not os.path.isfile(stats_file): # Collect stats.
        model_copy = model
        distiller.utils.assign_layer_fq_names(model_copy)
        collector = QuantCalibrationStatsCollector(model_copy)
        with collector_context(collector):
            val_loss = evaluate(16, config, model_copy, test_data, None)
        collector.save(stats_file)

    # Basic quantizer defintion
    quantizer = PostTrainLinearQuantizer(model,
                                    mode="SYMMETRIC",  # As was suggested in GNMT's paper
                                    model_activation_stats=stats_file,
                                    bits_activations=8,
                                    bits_parameters=8,
                                    bits_accum=32)
    # We take a look at the replacement factory:
    for t, rf in quantizer.replacement_factory.items():
        print("Replacing '{}' modules using '{}' function".format(t.__name__, rf.__name__))

    dummy_input = (torch.ones(1, 2).to(dtype=torch.long),
               torch.ones(1).to(dtype=torch.long),
               torch.ones(1, 2).to(dtype=torch.long))
    quantizer.prepare_model(dummy_input)`

How would I save my quantizer.model into a checkpoint like shown in image_classifier?

Best,
Rohan

**Comment by nzmora** [comment]
Hi @rdoshi96 ,

The bottom half of your code (i.e. starting from the line `quantizer = PostTrainLinearQuantizer(...)` is basically equivalent to:
https://github.com/NervanaSystems/distiller/blob/0036011d2141c665ae5152283dcd24ae9a08fa34/distiller/apputils/image_classifier.py#L825-L829

As you can see from the code, after you invoking `quantizer.prepare_model`, you can directly save the checkpoint: https://github.com/NervanaSystems/distiller/blob/0036011d2141c665ae5152283dcd24ae9a08fa34/distiller/apputils/image_classifier.py#L833-L837

So the answer is that after invoking `quantizer.prepare_model`, the weights are quantized and you can invoke `apputils.save_checkpoint` as usual.  Now, remember that these are saved as FP32 tensors, containing values that have been quantized (as explained https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)#quantization).

Cheers,
Neta
