### ISSUE TITLE
Compress a trained model

### ISSUE THREAD

**Issue by TranThanh96** [NervanaSystems/distiller#394]
Hi all,
This framework is like compress model in the training process.
But if I have a trained model, how can I compress it?

**Comment by andyqian2015** [comment]
@TranThanh96  Do you know how to use the compress model, when compress process has executed?when I run the weights file, the gpu memory are still the same as before, how it comes?

**Comment by nzmora** [comment]
Hi @TranThanh96,
There are many examples of post training quantization.  You can use the API to prune modules w/o retraining, but you will probably suffer from a big accuracy loss.  Therefore, our examples show pruning with fine-tuning.

Cheers
Neta

**Comment by nzmora** [comment]
Hi @andyqian2015,

To find out why the GPU memory size is unchanged, you may refer to Distiller's [FAQ](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)#quantization).

Cheers,
Neta

**Comment by levzlotnik** [comment]
Hi,
Closing this issue due to staleness. Feel free to reopen if there are further questions.
