### ISSUE TITLE
Issue while running compare_executions.ipynb. Function add_experiment not defined

### ISSUE THREAD

**Issue by ajayhk** [NervanaSystems/distiller#396]
While running the Jupyter notebook to compare two executions, get the below error
Cannot find add_experiment function anywhere in the code base either

> ---------------------------------------------------------------------------
> 
> NameError                                 Traceback (most recent call last)
> <ipython-input-2-f8b269807816> in <module>
>      12 
>      13 for experiment in experiment_files:
> ---> 14     add_experiment(axs, tags, experiment[0], label=experiment[1])
>      15 plt.tight_layout()
>      16 
> 
> NameError: name 'add_experiment' is not defined

**Comment by nzmora** [comment]
Hi @ajayhk ,
Thanks for pointing this out.  This is a hectic period for us, so it'll take me a few days to look into this.  
Thanks for your patience, Neta
