### ISSUE TITLE
Quantization dequanitze flag

### ISSUE THREAD

**Issue by hoseung2** [NervanaSystems/distiller#398]
Hi, while looking at the quantization function I found that there is a dequantize flag.
But as I think, the network should be forwarded to the dequantized value.
What's the purpose of the dequantize flag?

In other words, what's the difference between dequantized and non-dequantized cases?

Thank you.

**Comment by guyjacob** [comment]
I'm not sure what you mean by "the network should be forwarded to the dequantized value", but in any case, this is a utility function called from many places:

In some cases we want to just get the effect of quantization but still let the model run with float tensors (aka "fake-quantization"). This is common in quantization-aware training scenarios. In these cases we'll set `dequantize=True`.

In other cases we want to quantize a tensor and keep working on the quantized values. This happens in post-training quantization.

**Comment by hoseung2** [comment]
That's what I exactly wanted to know.

Thank you so much
