### ISSUE TITLE
There is probelm in usage of Documentation

### ISSUE THREAD

**Issue by zxb1489479870** [NervanaSystems/distiller#4]
When I run the sample code: $time python3 compress_classifier.py -a alexnet --lr 0.005 -p 50 ../../../data.imagenet -j 44 --epochs 90 --pretrained --compress=../imagenet/alexnet/pruning/alexnet.schedule_sensitivity.yaml,

I find it cannot work ,  it says cannot find the alexnet.schedule_sensitivity.yaml file.  I  think  the compress should be "../sensitivity-pruning/alexnet.schedule_sensitivity.yaml". Thanks.

**Comment by nzmora** [comment]
Hi,
You are correct that the path to the compression schedule is incorrect - thank you for finding this issue.
Are you referring to the mistake in the documentation ('usage' page), or did you find it in a different place?

Thanks,
Neta

**Comment by zxb1489479870** [comment]
It's a mistake in the documentation ('usage' page).

**Comment by nzmora** [comment]
Fixed and closing the issue.
Thanks @zxb1489479870 !
