### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by 2020zyc** [NervanaSystems/distiller#404]
Hi

Does distiller installation support cuda10.1? 

I meet two errors after installed.

One is "OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 32: Resource temporarily unavailable; OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max"

The other is "segmentation fault" when I import distiller

Hope for any suggestion, thanks much

**Comment by levzlotnik** [comment]
Hi @2020zyc ,

We haven't tested cuda10.1, however it shouldn't be an issue because our communication with cuda is only via PyTorch. Could you maybe provide more information on the error? e.g. Python stack trace?

Thanks,
Lev

**Comment by nzmora** [comment]
The error you're getting (hitting RLIMIT_NPROC limit) is probably related to the configuration of your machine/user (RLIMIT_NPROC is the number of processes the user you are using can own).  You can look at the output of `cat /proc/1/limits` to see you system's limits.

Good luck,
Neta
