### ISSUE TITLE
some questions of tutorial of Pruning Filters & Channels

### ISSUE THREAD

**Issue by shixinlishixinli** [NervanaSystems/distiller#417]
hi 
i have some questions of tutorial of Pruning Filters & Channels(https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html). i have no idea how to run this tutorial and which file i can use. if i want to prune VGG16, how can i do it ?

best
lisa shi

**Comment by jonathanbonnard** [comment]
Hi,
go check the examples directory, you have some .yaml files for every pruning category. 
"examples/pruning_filters_for_efficient_convnets/vgg19.schedule_filter_rank.yaml"
In the yaml files, you have a comment section which tells you what you have to type, and the pruner policies you want to adopt below.

> time python3 compress_classifier.py -a=vgg19 -p=50 ../../../data.imagenet --epochs=10 --lr=0.00001 --compress=../pruning_filters_for_efficient_convnets/vgg19.schedule_filter_rank.yaml --pretrained

Just change VGG19 in this example by VGG16 and the corresponding layers you want to compress

**Comment by cz3792** [comment]
if i want to change the model such as SSD or yolo, what should i do ? what documents do i need to do?

**Comment by levzlotnik** [comment]
> if i want to change the model such as SSD or yolo, what should i do ? what documents should i change ?

Hi @cz3792 ,
SSD or YOLO are object detection models, not classifiers. For treating them - refer to `examples/object_detection_compression` where I've implemented and example of pruning FastRCNN models.

**Comment by levzlotnik** [comment]
Hi,
Closing this issue due to staleness. Feel free to reopen if you have further questions.
