### ISSUE TITLE
Do you have a plan to implement INQ in distiller?

### ISSUE THREAD

**Issue by shengwenLeong** [NervanaSystems/distiller#42]
Hi,
  I read the distiller's documentation carefully and find it mentioned the INQ method proposed by Zhou.A. And now the Distiller does not support this method, so I want to know there is any plan to implement INQ in distiller? Thanks

**Comment by shengwenLeong** [comment]
Ok, Thanks for your reply. I will try to implement it by myself. if I encounter any important problem, I will consult you. Thanks.

**Comment by guyjacob** [comment]
Closing for now, feel free to re-open or open a new issue as needed. Thanks.
