### ISSUE TITLE
Modify a bug in ranked_structures_pruner.py while running AMC

### ISSUE THREAD

**Issue by csc12138** [NervanaSystems/distiller#429]
While running AMC, there is an error:
in the file distiller/distiller/pruning/ranked_structures_pruner.py
op_type is not defined,

After reviewing author's modification history, in the previous version of this file, in this function: "rank_and_prune_channels":
op_type = 'conv' if param.dim() == 4 else 'fc'

However, for the current version, this line of code is removed, so I guess, something like this should be added into the current version in order to fix this bug

**Comment by nzmora** [comment]
Thanks @csc12138, what's the command-line you are executing?

**Comment by wangyidong3** [comment]
Thanks @csc12138,  I got the same error, and then tried the way @csc12138 mentioned to solve it.
My command is :
`python3 amc.py --arch=resnet20_cifar /media/don/datasets/datasets/cifar-10-batches-py --resume=../../ssl/checkpoints/checkpoint_trained_dense.pth.tar  --amc-action-range 0.05 1.0 --amc-target-density=0.5 -p=50 --etes=0.075 --amc-ft-epochs=0 --amc-prune-pattern=channels --amc-prune-method=fm-reconstruction --amc-agent-algo=DDPG --amc-cfg=auto_compression_channels.yaml --amc-rllib=hanlab -j=1`
I removed  "--amc" in original command-line as it is not recognized. 

Here are other issues and temperay solutions I found when I run the command, hope it is useful for others.
AssertionError : assert self.removed_macs_pct >= 1 - self.amc_cfg.target_density - 0.002 # 0.01
![assertionError](https://user-images.githubusercontent.com/2003294/69759487-1cf1e380-11c7-11ea-993c-5b3b8ce796f3.png)
it is difficult to adjust the parameter to pass the assertion, so I comment this line to continue.

One more similar issue is that: name 'ALMOST_ONE' is not defined
![ALMOST_ONE](https://user-images.githubusercontent.com/2003294/69759501-254a1e80-11c7-11ea-97fd-6c135e253dca.png)
I re-add ALMOST_ONE = 0.9999 in environment.py line38, then training started properly.

**Comment by nzmora** [comment]
Thanks @csc12138, @wangyidong3 for opening this issue and suggesting the solution.  I've pushed a fix.  Let me know if there are further problems with this example.
Thanks!
Neta

**Comment by levzlotnik** [comment]
Hi,

Closing this issue as it seems resolved.
