### ISSUE TITLE
why the "direct" quantization operate can't make model smaller？

### ISSUE THREAD

**Issue by souseiki** [NervanaSystems/distiller#43]
I have tried to use Symmetric Linear Quantization to quantize my model. I'm wondering why the parameters of model is still the float (11.) rather than int (11).  The Quantization  seems  only help me to change the parameters from float (11.12345) into integer of float (11.)

**Comment by vinutah** [comment]
https://github.com/NervanaSystems/distiller/issues/22#issuecomment-403562263
should answer your question

**Comment by guyjacob** [comment]
@vinutah thanks for your responses!
