### ISSUE TITLE
bfloat16 quantization support

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#433]
Can Distiller support bfloat16 quantization?

**Edit:** From my understanding, there's no CUDA support for bfloat16. Therefore, the focus of this issue is post-training quantization specifically.

**Comment by levzlotnik** [comment]
Pytorch itself should soon add support for bfloat16 quantization, for now they say it's only for the CPU:
https://github.com/pytorch/pytorch/issues/23149

**Comment by barrh** [comment]
Just to make sure we're on the same page, there is no bfloat quantization is PyTorch master (only conversion/casting), nor there is any PR aimed to enhance support of bfloat toward Pytorch v1.4, at this time. Current Pytorch support is for having bfloat16 type, which is great by itself, but that's not to be mixed with quantization support.

From my understanding, there's no CUDA support for bfloat16. Therefore, the focus of this issue is post-training quantization specifically.

**Comment by levzlotnik** [comment]
As far as I know, conversion is in fact quantization. Otherwise I'm not sure what you mean

**Comment by levzlotnik** [comment]
Hi,
Closing this issue due to staleness.
