### ISSUE TITLE
ImportError: No module named 'distiller'

### ISSUE THREAD

**Issue by kaijunhuang** [NervanaSystems/distiller#438]
When I use quantization,no matter what use PostTrainLinearQuantizer or QuantAwareTrainRangeLinearQuantizer,the model that I trained,always has this error:
"ImportError: No module named 'distiller'"
my train script as flows:
PostTrainLinearQuantizer :python compress_PSE_dector.py  -a mobilenet_v2_pse ../../../../data.imagenet/  --resume ./logs/2019.12.04-180404/checkpoint.pth.tar -b 16 --quantize-eval --evaluate

**Comment by kaijunhuang** [comment]
QuantAwareTrainRangeLinearQuantizer:
python compress_PSE_dector.py  -a mobilenet_v2_pse ../../../../data.imagenet/  --compress=../quantization/quant_aware_train_linear_quant.yaml --lr 0.0001 -b 16 --epochs 99 

where compress_PSE_dector.py and mobilenet_v2_pse are my defined net.It train well on no-quantization

**Comment by kaijunhuang** [comment]
when I use the model that I trained to inference,it has this error:
"ImportError: No module named 'distiller'"

**Comment by guyjacob** [comment]
Hi @kaijunhuang.
Did you follow the installation instructions in the README? 
See https://github.com/NervanaSystems/distiller#installation.

**Comment by kaijunhuang** [comment]
@guyjacob It train well on no-quantization,just to use the model to inference.

**Comment by guyjacob** [comment]
Common root causes for this 'ImportError' is not installing Distiller properly, or not activating the virtual environment (in case you installed it in a virtual environment). That's why I asked about that.

So just to be sure - if you open a Python console and simply run `import distiller` - does that work?
* If it doesn't, then it's likely an installation / virtual environment issue.
* If it works, then please share your script (or some minimal example of how to re-produce the error).

Thanks

**Comment by kaijunhuang** [comment]
@guyjacob Thank you for your reply. Anyway,I want to use the quantization model for mobile devices without distiller environment.

**Comment by kaijunhuang** [comment]
@guyjacob my issue is similar as #47,I'm looking forward to your reply.Thank you~

**Comment by guyjacob** [comment]
If you're referring to loading a checkpoint that contains a model quantized with Distiller - indeed the checkpoint contains the quantizer type, which requires importing Distiller before loading the checkpoint.

At the moment, models quantized with Distiller can't run independent of Distiller as-is. We're working on an option to convert models quantized with Distiller to PyTorch 1.3 compatible quantized models - then you'll be able to export the model to a mobile environment.
