### ISSUE TITLE
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /pytorch/aten/src/ATen/native/cuda/Dropout.cu:147

### ISSUE THREAD

**Issue by cindybrain** [NervanaSystems/distiller#440]
I am so sad that every time I will met the same problem: no kernel image is available on the device
Ubuntu:16.04.6 LTS
Nvidia GeForce 920M (compute capability: 3.5)
Nvidia driver:418
cuda:10.1
pytorch:1.3.1

 
When I run the "time python3 main.py --cuda --epochs 40 --tied --wd=1e-6", i met the error info:
Preparing data (this may take several seconds)...
Done
Log file for this run: /home/hs/distiller/examples/word_language_model/logs/2019.12.06-163830/2019.12.06-163830.log

--------------------------------------------------------
Logging to TensorBoard - remember to execute the server:
> tensorboard --logdir='./logs'

THCudaCheck FAIL file=/pytorch/aten/src/ATen/native/cuda/Dropout.cu line=147 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    train(epoch, optimizer, compression_scheduler)
  File "main.py", line 227, in train
    output, hidden = model(data, hidden)
  File "/home/hs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hs/distiller/examples/word_language_model/model.py", line 54, in forward
    emb = self.drop(self.encoder(input))
  File "/home/hs/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hs/env/lib/python3.5/site-packages/torch/nn/modules/dropout.py", line 54, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/hs/env/lib/python3.5/site-packages/torch/nn/functional.py", line 807, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /pytorch/aten/src/ATen/native/cuda/Dropout.cu:147
Command exited with non-zero status 1
28.58user 1.11system 0:28.99elapsed 102%CPU (0avgtext+0avgdata 1271664maxresident)k
0inputs+16outputs (0major+213751minor)pagefaults 0swaps

![1](https://user-images.githubusercontent.com/24526363/70310728-5243a480-184b-11ea-9380-60dd331477fe.png)

![2](https://user-images.githubusercontent.com/24526363/70310735-540d6800-184b-11ea-9832-24cdc8d402af.png)

![3](https://user-images.githubusercontent.com/24526363/70310748-58398580-184b-11ea-91bd-7ca48949e548.png)

**Comment by barrh** [comment]
Unfortunately, your GPU is not supported by Pytorch v1.3.1 which Distiller depends on. i.e. only compute capab. >= 3.7 are supported.
Once you have verified Pytorch is the source of the problem, regardless of Distiller.
I would suggest the following mitigation alternatives:
0. Run the script on CPU, without CUDA.
1. Try to install torch==1.2, and see if the script works.
Although, this could fail something during runtime, it's the "cheaest" solution, so worth a shot.
2. Build Pytorch from source specifically fro your GPU compute capability.

Good luck

**Comment by cindybrain** [comment]
Thanks so much. I will have try :)

**Comment by cindybrain** [comment]
> Unfortunately, your GPU is not supported by Pytorch v1.3.1 which Distiller depends on. i.e. only compute capab. >= 3.7 are supported.
> Once you have verified Pytorch is the source of the problem, regardless of Distiller, I would suggest the following mitigation alternatives:
> 0. Run the script on CPU, without CUDA.
> 
> 1. Try to install torch==1.2, and see if the script works.
>    Although, this could fail something during runtime, it's the "cheapest" solution, so worth a shot.
> 2. Build Pytorch from source specifically for your GPU compute capability.
> 
> Good 

> Unfortunately, your GPU is not supported by Pytorch v1.3.1 which Distiller depends on. i.e. only compute capab. >= 3.7 are supported.
> Once you have verified Pytorch is the source of the problem, regardless of Distiller, I would suggest the following mitigation alternatives:
> 0. Run the script on CPU, without CUDA.
> 
> 1. Try to install torch==1.2, and see if the script works.
>    Although, this could fail something during runtime, it's the "cheapest" solution, so worth a shot.
> 2. Build Pytorch from source specifically for your GPU compute capability.
> 
> Good luck

Thanks again. I solve it by install torch==1.2.0, and right now i don't meet any other problems. By the way, when I run the scripts for pruning filters/channels on CPU, i find that the spasity is always 0.00, but on GPU, it works ok!

**Comment by killerzula** [comment]
Hi @cindybrain, did installing torch==1.2 solve the issue or does the problem persist?

**Comment by cindybrain** [comment]
Hi @killerzula , It works ok in the previous vision of distiller by installing torch==1.2, but maybe not in the newest vision. Right now I run on a different machine with torch==1.3.1

**Comment by skmalviya** [comment]
It also sorts out my problem. torch==1.4 was emitting the same error earlier but. When I install torch==1.2, It ran without any issue!!!
