### ISSUE TITLE
export model after filter or channel pruning

### ISSUE THREAD

**Issue by smxzxcghl** [NervanaSystems/distiller#447]
When I use --export-onnx to export a model after pruning, the size can't fits to the original model.I use command line like this:
`time python3 compress_classifier.py -a=resnet56_cifar  ../../../../data.cifar10 --resume-from=checkpoint_finetuned.pth.tar  --export-onnx=resnet56_pf.onnx`
The checkpoint is resnet56 after channel pruning, provided in examples/ssl.The two line of result is :

```
size mismatch for layer3.8.bn1.weight: copying a param with shape torch.Size([45]) from checkpoint, the shape in current model is torch.Size([64]).
size mismatch for layer3.8.conv2.weight: copying a param with shape torch.Size([64, 45, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
```
The size of model changed,  --export-onnx maybe can only export models whose size unchanged.
Is there any method to export model whose structure changes?

**Comment by smxzxcghl** [comment]
I modified code in image_classifier.py to solve this problem.

**Comment by nzmora** [comment]
Hi @smxzxcghl ,

What was the modification?
Cheers
Neta

**Comment by smxzxcghl** [comment]
Hi Neta,
I just add code about exporting model to onnx in the end of test function in image_classifier.py
Ghl
------------------ Original ------------------
