### ISSUE TITLE
Any plans for integrating Intel's 4 bit quantization work?

### ISSUE THREAD

**Issue by masahi** [NervanaSystems/distiller#449]
Hi, do you have any plans for integrating Intel's 4 bit quantization work that they published recently at Neurips 2019 (the paper and code below)? Their demo code quantizes the value of tensors, but the actual operations are performed on fp32, so I think it fits well with distiller's quantization mechanism.

https://papers.nips.cc/paper/9008-post-training-4-bit-quantization-of-convolutional-networks-for-rapid-deployment.pdf
https://github.com/submission2019/cnn-quantization

**Comment by guyjacob** [comment]
Yes, this actually ongoing. See #432.

**Comment by masahi** [comment]
Thanks! I was not aware of this newer work. Very good to know the PR is already on going.
