### ISSUE TITLE
How to understand the 'arch' and 'dataset' for 'thinner'

### ISSUE THREAD

**Issue by RizhaoCai** [NervanaSystems/distiller#456]
Hello,

I would like to use the distiller to conduct structured pruning (i.e. filter pruning or channel pruning) for my rfb-net model for a detection task.

How to understand the args 'arch' and 'dataset' for the thinner?
 I am going to conduct pruning for my rfb-net and will fine-tune the model on my own detection dataset. What should I do? Just ignore these two args?

This question is the same as Ringhu's
![image](https://user-images.githubusercontent.com/37952703/71657721-0c132f80-2d7c-11ea-8b58-11f143d7d2df.png)

By looking into the source code at distiller/thinning.py, as shown below, 'arch' seems useless.

```
__all__ = ['ThinningRecipe', 'resnet_cifar_remove_layers',
           'StructureRemover',
           'ChannelRemover', 'remove_channels',
           'FilterRemover',  'remove_filters',
           'contract_model',
           'execute_thinning_recipes_list', 'get_normalized_recipe']


def contract_model(model, zeros_mask_dict, arch, dataset, optimizer):
    """Contract a model by removing filters and channels

    The algorithm searches for weight filters and channels that have all
    zero-coefficients, and shrinks the model by removing these channels
    and filters from the model definition, along with any related parameters.
    """
    remove_filters(model, zeros_mask_dict, arch, dataset, optimizer)
    remove_channels(model, zeros_mask_dict, arch, dataset, optimizer)


def remove_channels(model, zeros_mask_dict, arch, dataset, optimizer):
    """Contract a model by removing weight channels"""
    sgraph = _create_graph(dataset, model)
    thinning_recipe = create_thinning_recipe_channels(sgraph, model, zeros_mask_dict)
    apply_and_save_recipe(model, zeros_mask_dict, thinning_recipe, optimizer)
    return model


def remove_filters(model, zeros_mask_dict, arch, dataset, optimizer):
    """Contract a model by removing weight filters"""
    sgraph = _create_graph(dataset, model)
    thinning_recipe = create_thinning_recipe_filters(sgraph, model, zeros_mask_dict)
    apply_and_save_recipe(model, zeros_mask_dict, thinning_recipe, optimizer)
    return model
```

**Comment by RizhaoCai** [comment]
After looking back to the source code, it seems that the arch and dataset are just for setting dummy_input for tracking the graph. Such a setting a quite not user-friendly because users may use distiller with their own dataset and architecture.

**Comment by nzmora** [comment]
Hi @RizhaoCai 
You are correct: the API creates an unneeded dependency on the architecture and dataset (I originally did this for convenience) and should be refactored.
Thanks
Neta

**Comment by RizhaoCai** [comment]
> Hi @RizhaoCai
> You are correct: the API creates an unneeded dependency on the architecture and dataset (I originally did this for convenience) and should be refactored.
> Thanks
> Neta

Got it. Thanks.

**Comment by longzeyilang** [comment]
I got the same question, how to do it?
