### ISSUE TITLE
AttributeError: module 'parser' has no attribute 'add_cmdline_args'

### ISSUE THREAD

**Issue by Blue-Eagle-10** [NervanaSystems/distiller#465]
I have installed all the environments according to the readme. When I run this 8-bit quantized code<python compress_classifier.py -a resnet20_cifar ../../../data.cifar10 --resume ../ssl/checkpoints/checkpoint_trained_dense.pth.tar --quantize-eval --evaluate>, I get the following error. How can I solve this problem?

Traceback (most recent call last):
  File "compress_classifier.py", line 210, in <module>
    main()
  File "compress_classifier.py", line 74, in main
    args = parser.add_cmdline_args(classifier.init_classifier_compression_arg_parser()).parse_args()
AttributeError: module 'parser' has no attribute 'add_cmdline_args'

**Comment by nzmora** [comment]
Hi @Blue-Eagle-10,

Please send the log file of this run. 
Thanks
Neta

**Comment by Blue-Eagle-10** [comment]
Hello @ Neta,
Thank you for your reply. I uploaded my log file to the system and asked for your answer. thank you very much!
Blueeagle

![log](https://user-images.githubusercontent.com/24905967/72665916-00945980-3a48-11ea-960d-094431365e66.jpg)

**Comment by nzmora** [comment]
Thanks @Blue-Eagle-10 ,
I see that you're using Windows, which we do not support, and that may be the source of the problems.  
Can you try this:
![image](https://user-images.githubusercontent.com/31280975/72667155-4d186e80-3a21-11ea-98fc-dbaaeb2c88e2.png)
That is, in the same venv in which you run the failing code, invoke the Python interpreter, then `import parser` and `dir(parser)` to see all of the symbols in the namespace. If you don't see the `get_cmdline_args` member, then I think there's something wrong with the environment you've created, or it's a Windows compatibility issue.

Cheers,
Neta

**Comment by Blue-Eagle-10** [comment]
Hello @ Neta,
Thank you for your reply！I now reload Ubuntu, and then retest the code. Thank you very much for your answers and benefit a lot.

your sincerely

Blueeagle

**Comment by Blue-Eagle-10** [comment]
Hello@Neta,
I installed all the environments and packages according to the tutorial and got this error when running the code: ModuleNotFoundError: No module named 'gitdb.utils.compat'.
Ask for help, how can I resolve this error? thank you very much！
![2020-02-22 07-10-17](https://user-images.githubusercontent.com/24905967/75047971-b8fb6480-5502-11ea-8499-1a7f7e5ba4b7.png)

**Comment by retaw106** [comment]
> 
> 
> Hello@Neta,
> I installed all the environments and packages according to the tutorial and got this error when running the code: ModuleNotFoundError: No module named 'gitdb.utils.compat'.
> Ask for help, how can I resolve this error? thank you very much！
> ![2020-02-22 07-10-17](https://user-images.githubusercontent.com/24905967/75047971-b8fb6480-5502-11ea-8499-1a7f7e5ba4b7.png)

I just encountered the same problem. It's because gitdb has upgraded recently. Execute "pip install gitdb==0.6.4", then it's okay.

**Comment by nzmora** [comment]
Thanks @retaw106 ,

@levzlotnik fixed this issue yesterday with [this commit](https://github.com/NervanaSystems/distiller/commit/07c14e707d60256f67bbf603b2260064d33eb018).  Do you know if you've used this commit when you saw the problem?

Thanks!
Neta

**Comment by retaw106** [comment]
> 
> 
> Thanks @retaw106 ,
> 
> @levzlotnik fixed this issue yesterday with [this commit](https://github.com/NervanaSystems/distiller/commit/07c14e707d60256f67bbf603b2260064d33eb018). Do you know if you've used this commit when you saw the problem?
> 
> Thanks!
> Neta

No, I used previous commit.
