### ISSUE TITLE
gitdb and gitdb2 version error in requirements.txt

### ISSUE THREAD

**Issue by retaw106** [NervanaSystems/distiller#477]
Gitdb 4.0.0 and gitdb2 4.0.1 has been removed from pypi. So current requirements
```
gitdb==4.0.0
gitdb2==4.0.1
```
would cause errors.

**Comment by retaw106** [comment]
And I'm confused why using so many restrict requirements.
For me, those restrict requirements frequently brings problems.

**Comment by guyjacob** [comment]
Regarding `gitdb`, it's related to #475. I just pushed another fix which removes these requirements. Please pull the latest and see if it works.

Regarding restricting versions in general - it ensures that we have a stable, known set of dependencies which we know that works. If you use a virtual environment dedicated to Distiller (as per our [README](https://github.com/NervanaSystems/distiller#create-a-python-virtual-environment)), then this should not interfere with any other packages/libraries.
