### ISSUE TITLE
Trouble implementing KD

### ISSUE THREAD

**Issue by JuanDavidG1997** [NervanaSystems/distiller#483]
Hi!
First aff all awesome code. 
I am trying to compare different pruning and distillation methods. But I am having a very hard time implementing the KD.
Are you planning to add it to the yaml any time soon?
Is there any way to have a detailed tutorial about it?
Thank you!

**Comment by guyjacob** [comment]
Hi @JuanDavidG1997,

Did you check out the docs here:
https://nervanasystems.github.io/distiller/schedule.html#knowledge-distillation
And couldn't get it to work?

Unfortunately, I don't think we'll be making it configurable via YAML. As detailed in the docs, we did implement a "helper" set of command line arguments you can add to your script that allow you to configure KD from command-line.

**Comment by JuanDavidG1997** [comment]
Yes I did...
I don't really understand how to implement de compression scheduler and where to give the training data...
Even after checking de example of imagenet
