### ISSUE TITLE
Can early exit technology be applied to object detection tasks?

### ISSUE THREAD

**Issue by bupt-renpei** [NervanaSystems/distiller#491]
Such as YOLO, SSD, RCNN? At the moment it looks like it's only applied to classification tasks.

**Comment by nzmora** [comment]
Hi @bupt-renpei ,

Yes, in general you can add EE branches to any model.  See is [this](https://github.com/NervanaSystems/distiller/wiki/Adding-Early-Exit-branch) helps you.

Cheers,
Neta

**Comment by bupt-renpei** [comment]
Hi @nzmora 

Thanks for your patient reply! I will try it on object detection models.

Best,
Pei
