### ISSUE TITLE
How to use distiller in colab?

### ISSUE THREAD

**Issue by Midhilesh29** [NervanaSystems/distiller#493]
I have typed following command to install distiller with following commands

```
!git clone https://github.com/NervanaSystems/distiller.git
!cd distiller && pip3 install -e .
from distiller.models import create_model
```
I got the following error

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-b69f00e456ee> in <module>()
----> 1 from distiller.models import create_model

ModuleNotFoundError: No module named 'distiller.models'
```
Please help me to solve this

**Comment by nzmora** [comment]
Hi @Midhilesh29,

The correct command sequence is:
```
!git clone https://github.com/NervanaSystems/distiller.git
%cd distiller
!pip3 install -e .
from distiller.models import create_model
```

When you perform `!cd distiller` you're just changing the subshell that runs the `cd` command.  Use`%cd distiller` to change the current working directory for the notebook environment (confirm this using `!pwd`).  
See: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-cd

Cheers,
Neta

**Comment by Midhilesh29** [comment]
Thank you!
