### ISSUE TITLE
How to apply post quantization on any object detectors?

### ISSUE THREAD

**Issue by Midhilesh29** [NervanaSystems/distiller#495]
Hi, I am currently working on post quantize an object detection model. I can find only resource for guiding beginners to post quantize an object classification model. 
I request you to help me with a sample code such that I can learn from that.

**Comment by guyjacob** [comment]
Hi @Midhilesh29. If you look in our examples, you'll see examples for post-training quantization on various types of workloads - image classification, language model, translation and recommendation systems. Indeed, for object detection we only have sample code for pruning.

Unfortunately, we don't have the bandwidth to add an object detection quantization tutorial.

The next best thing I could offer you is to take a look specifically at the language model and/or GNMT examples, which are give as Jupyter notebook tutorials. These are presented in fairly step-by-step fashion, so they might give you a good starting point.

If you have any specific questions, you can always open another issue.
