### ISSUE TITLE
Lack of EltwiseSub

### ISSUE THREAD

**Issue by killerzula** [NervanaSystems/distiller#496]
Hi,
The docs at distiller mention that [direct tensor operations are to be replaced with equivalent modules](https://nervanasystems.github.io/distiller/prepare_model_quant.html#replace-direct-tensor-operations-with-modules). For this purpose a few classes have been implemented in the file [eltwise.py](https://github.com/NervanaSystems/distiller/blob/master/distiller/modules/eltwise.py). For example, `+` operation or `torch.add` is to be replaced with `distiller.modules.EltwiseAdd` which is a subclass of `nn.Module`.

What bothers me is that why are only addition, multiplication, and division implemented in the eltwise.py file? Surely, implementing subtraction as well is not difficult at all.

Is there a specific reason or some catch that I am not seeing? For the time being I will implement my own EltwiseSub but I would really like to know your take on this.

**Comment by nzmora** [comment]
Hi @killerzula ,

There is no catch :-)
Subtraction was not implemented because we didn't come across a network that required it.  We will be happy to get a PR from you with the code for a `distiller.modules.EltwiseAdd` implementation.
Cheers
Neta
