### ISSUE TITLE
Can I reproduce the figures in Distiller docs?

### ISSUE THREAD

**Issue by hcygeorge** [NervanaSystems/distiller#507]
Hi,
The figure of filter pruning in Distiller docs are useful for understanding.

I produced figures on my own but refer to your figures design.
Can I use these reproduced figures in my articles?
I will cite the website below.
https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html

**Comment by guyjacob** [comment]
Hi @hcygeorge. Sure, you can use the figures citing the webpage you mentioned. If you could send as a link when your articles are done, that would be great.
