### ISSUE TITLE
two things to confirm about weights and activations quantization

### ISSUE THREAD

**Issue by hunterkun** [NervanaSystems/distiller#52]
1. When setting the `train_with_fp_copy` true, you change the attribute of conv/fc layer. You substitute `conv.weights` with `conv.float_weights` and conv.weights become the buffer instead parameter.  The forward pass of conv/fc layer still use conv.weights, quantized weights, which is determined by Pytorch default conv implementation. But  in backward pass, the gradients calculated with respect to q_weights(quantized weights) is stored in `float_weights.gard` rather than `weights`due to it has no grad attribute. So you implicitly back-prop the grad with respect to quantized weights to the grad with full-precision weights using straight-through estimator namely both are equal.
2. You implement activation quantization by replacing relu layer with new own-defined layer. Also you again directly make the gradient with respect of activations before and after quantisation equal using STE.
So I want to confirm to you whether there are some misunderstanding in above points.

**Comment by guyjacob** [comment]
No misunderstandings - everything you wrote is accurate :)
