### ISSUE TITLE
Some confusions about pruning procedure

### ISSUE THREAD

**Issue by hunterkun** [NervanaSystems/distiller#53]
You set the mask for parameters in model on the beginning of epoch. Considering you may set two or more different pruners for parameters in different layers,  it is reasonable that the `set_param_mask` is called in  `on_epoch_begin` of  Class `PruningPolicy`. 

But I think masker's method `apply_mask` should not be called in `on_minibatch_begin` because  you would call the `apply_mask` method two  or more times  when you have two or more pruners in your policies. I think calling it one time is enough due to `zeros_mask_dict` have included all parameters you want to prune although the results are same no matter how many times you call it. 

Interestingly, I found you implement this idea in `on_minibatch_end` in `scheduler.py`, which calls `apply_mask` only one time by using`weights_are_masked` flags. 

The second question is that you call `apply_mask` on the end of minibatch due to the weights are updated during the backward pass. However, I think it is no need to do that. Because the weights you mask cannot be updated due to it's `grad` attribute has been masked(or set to zero) in backward by using `register_hook` function.

**Comment by nzmora** [comment]
Hi,
Both of your questions/comments are important. 

1. I tried to keep ```CompressionScheduler``` decoupled from ```PruningPolicy```.  That means, among other things, that ```CompressionScheduler``` doesn't know what ```PruningPolicy``` does in ```on_epoch_begin```.  Therefore ```CompressionScheduler``` should not be responsible for this optimization you suggest.  
On the other hand, two instances of ```PruningPolicy``` don't know about each other's existence, and so they also can't be responsible for this optimization.
I can think of a way to resolve this, but it involves ```PruningPolicy``` passing back information to ```CompressionScheduler``` - and that would complicate matters and would create a little coupling between the two classes.  I prefer to avoid this, unless this optimization is important.  Do you think this would save a significant amount of time? I haven't measured it, but my intuition is that it is not significant.

2. You are correct.  This code has a bit of history behind it, so I want to give this a bit more thought and testing before removing.

Thanks!
Neta

**Comment by hunterkun** [comment]
Yeah, thanks for you pointing out this small easy-overlooked detail.  But it also means there is no need to mask the gradient of pruned weight using `register_hook`, so is it suitable to delete the `param.regsiter_hook(...)` in `scheduler.py`?

**Comment by nzmora** [comment]
You are quite correct! Thanks for this observation.  If you want, you can send us a PR with the fix, or I'll push one in a couple of days.
Cheers,
Neta
