### ISSUE TITLE
The problem of example command

### ISSUE THREAD

**Issue by TonightGo** [NervanaSystems/distiller#60]
Hi, nzmora:
   When I ran the command "python3 compress_classifier.py --arch simplenet_cifar ../../../data.cifar10 -p 30 -j=1 --lr=0.01", I got the following error:

2018-10-22 17:03:03,745 - Log file for this run: /home/project/compress/distiller-master/examples/classifier_compression/logs/2018.10.22-170303/2018.10.22-170303.log
2018-10-22 17:03:03,745 - Number of CPUs: 24
2018-10-22 17:03:03,850 - Number of GPUs: 8
2018-10-22 17:03:03,850 - CUDA version: 8.0.61
2018-10-22 17:03:03,850 - CUDNN version: 7102
2018-10-22 17:03:03,851 - Kernel: 4.4.0-98-generic
2018-10-22 17:03:03,851 - Python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
2018-10-22 17:03:03,851 - PyTorch: 0.4.0
2018-10-22 17:03:03,851 - Numpy: 1.14.3
2018-10-22 17:03:03,852 - Traceback (most recent call last):
  File "compress_classifier.py", line 686, in <module>
    main()
  File "compress_classifier.py", line 179, in main
    apputils.log_execution_env_state(sys.argv, gitroot=module_path)
  File "/home/project/compress/distiller-master/apputils/execution_env.py", line 78, in log_execution_env_state
    log_git_state()
  File "/home/project/compress/distiller-master/apputils/execution_env.py", line 56, in log_git_state
    repo = Repo(gitroot, search_parent_directories=True)
  File "/home/project/compress/distiller-master/env/lib/python3.5/site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/project/compress/distiller-master

2018-10-22 17:03:03,852 - 
2018-10-22 17:03:03,852 - Log file for this run: /home/project/compress/distiller-master/examples/classifier_compression/logs/2018.10.22-170303/2018.10.22-170303.log

How can I solve the problem？

**Comment by nzmora** [comment]
Hi,

When compress_classifier.py is invoked, it saves some information about the execution environment, to make it easier later to compare and recreate experiment executions.

We collect three pieces of information regarding the git environment: the current branch, is the git working area clean or dirty (i.e. are you working with some local changes), and the tag of the had of the local git repo.  See: https://github.com/NervanaSystems/distiller/blob/ab02df45374db22a22e160fdf518103b19819dcb/apputils/execution_env.py#L51-L66

This code searches up the directory tree, looking for your ```.git``` directory, but in your case it can't find this directory.  I suspect that you run the example in a directory above where you cloned distiller.  Is this correct?  Can you send more about your directory hierarchy?

BTW, you can bypass this specific issue, by placing this line in remark: https://github.com/NervanaSystems/distiller/blob/ab02df45374db22a22e160fdf518103b19819dcb/apputils/execution_env.py#L78

Cheers,
Neta

**Comment by TonightGo** [comment]
em, I cannot use git clone command for the reason of network yesterday, so I download the package alternatively. Now it's no longer a problem. Thank you very much!

> Hi,
> 
> When compress_classifier.py is invoked, it saves some information about the execution environment, to make it easier later to compare and recreate experiment executions.
> 
> We collect three pieces of information regarding the git environment: the current branch, is the git working area clean or dirty (i.e. are you working with some local changes), and the tag of the had of the local git repo. See:
> 
> [distiller/apputils/execution_env.py](https://github.com/NervanaSystems/distiller/blob/ab02df45374db22a22e160fdf518103b19819dcb/apputils/execution_env.py#L51-L66)
> 
> Lines 51 to 66 in [ab02df4](/NervanaSystems/distiller/commit/ab02df45374db22a22e160fdf518103b19819dcb)
> 
>      def log_git_state(): 
>          """Log the state of the git repository. 
>   
>          It is useful to know what git tag we're using, and if we have outstanding code. 
>          """ 
>          repo = Repo(gitroot) 
>          assert not repo.bare 
>   
>          if repo.is_dirty(): 
>              logger.debug("Git is dirty") 
>          try: 
>              branch_name = repo.active_branch.name 
>          except TypeError: 
>              branch_name = "None, Git is in 'detached HEAD' state" 
>          logger.debug("Active Git branch: %s", branch_name) 
>          logger.debug("Git commit: %s" % repo.head.commit.hexsha) 
> This code searches up the directory tree, looking for your `.git` directory, but in your case it can't find this directory. I suspect that you run the example in a directory above where you cloned distiller. Is this correct? Can you send more about your directory hierarchy?
> 
> BTW, you can bypass this specific issue, by placing this line in remark:
> 
> [distiller/apputils/execution_env.py](https://github.com/NervanaSystems/distiller/blob/ab02df45374db22a22e160fdf518103b19819dcb/apputils/execution_env.py#L78)
> 
> Line 78 in [ab02df4](/NervanaSystems/distiller/commit/ab02df45374db22a22e160fdf518103b19819dcb)
> 
>  log_git_state() 
> Cheers,
> Neta

em, I cannot use git clone command for the reason of network yesterday, so I download the package alternatively. Now it's no longer a problem. Thank you very much!

**Comment by nzmora** [comment]
Thanks, for bringing this up: I forgot that people can download the zip file!
I will add a graceful error handler in this case and then I'll close the issue again.

Thank you for reporting this!
Cheers,
Neta
