### ISSUE TITLE
The link in the getting started section on the readme is not available

### ISSUE THREAD

**Issue by stvreumi** [NervanaSystems/distiller#65]
As the title say, the link
- [Usage](https://nervanasystems.github.io/usage/index.html)
- [Tutorial: Using Distiller to prune a PyTorch language model](https://github.com/NervanaSystems/distiller/blob/master)
in the section "getting started" give me 404 message. Can you move or update these links?
Thanks.

**Comment by nzmora** [comment]
Thanks @stvreumi! 
I fixed the documentation bug.
Cheers,
Neta

**Comment by Slicerkao** [comment]
Hi, 
I'm afraid that the link dies again.

**Comment by nzmora** [comment]
Thanks @Slicerkao,
We didn't notice that a new version of mkdocs changed some of the page links.
Hopefully I got them all.
Cheers,
Neta
