### ISSUE TITLE
initialization for GradientRankedFilterPruner

### ISSUE THREAD

**Issue by gaojinw** [NervanaSystems/distiller#82]
hello:

In the initialization function of GradientRankedFilterPruner, it is using RandomRankedFilterPruner. Is it typo? IMHO, we should use super(GradientRankedFilterPruner, self) instead.

<img width="534" alt="2018-11-22 10 35 45" src="https://user-images.githubusercontent.com/17039618/48878460-6f752300-ee42-11e8-972f-0c5985caf63d.png">

thanks!

**Comment by nzmora** [comment]
Thanks!  Yes, this is an unfortunate cut & paste error.
I'll fix shortly.
Neta
