### ISSUE TITLE
Does quantization support zero-point?

### ISSUE THREAD

**Issue by qinjian623** [NervanaSystems/distiller#83]
Seems there isn't zero-point handling in the code.

So does distill support zero-point in quantization?

Thanks.

**Comment by qinjian623** [comment]
@guyjacob 
Thanks so much. 
Looking forward to it.

**Comment by qinjian623** [comment]
Hi @guyjacob 

This is my code with zero_point handling.

I'm not sure whether it is a solid implement.
It will influence the range of (min, max).

Thanks for your time.

`def weight_quantize_parameter(weight, bits=8):
    max_w = weight.max().item()
    min_w = weight.min().item()
    level = 2 ** bits - 1
    scale = (max_w - min_w) / level
    zero_point = round((0.0 - min_w) / scale)
    return scale, zero_point
`

**Comment by guyjacob** [comment]
Addressed in #95. Closing this.
