### ISSUE TITLE
Knowledge Distillation 

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#90]
I had read "Knowledge Distillation" [https://nervanasystems.github.io/distiller/schedule/index.html#knowledge-distillation](url)

Would you please help to give me a simple example about knowledge distillation?

**Comment by guyjacob** [comment]
If you're looking for examples of how to use knowledge distillation in Distiller, I updated a couple of the sample schedulers in the quantization samples dir with sample command lines and results - [FP32 sample](https://github.com/NervanaSystems/distiller/blob/master/examples/quantization/preact_resnet_cifar_base_fp32.yaml), [quantized sample](https://github.com/NervanaSystems/distiller/blob/master/examples/quantization/preact_resnet_cifar_dorefa.yaml).
If you're looking for an example of where knowledge distillation might be used in general, we have a nice [introduction](https://nervanasystems.github.io/distiller/knowledge_distillation/index.html) to the subject in our docs, with some links to papers using knowledge distillation with other compression methods.

**Comment by HKLee2040** [comment]
@guyjacob The quantization samples are what I need.  Thanks!
